# FAQ objects kb-0100 – kb-0113 (source: FAQ 2025 note; kb-0100 also merges the 55-doc detail from FAQ 2026 (2))
SRC25 = "FAQ 2025 — ESG webinars Q&A (Evernote, updated 2026-08-24)"
SRC26_1 = "EcoVadis FAQ 2026 (1) (Evernote, updated 2026-08-24)"
SRC26_2 = "EcoVadis FAQ 2026 (2) (Evernote, updated 2026-08-24)"

FAQS = [
{
 "id": "kb-0100",
 "slug": {"en": "55-document-limit-and-combining-documents",
          "fr": "limite-55-documents-et-regroupement",
          "nl": "limiet-55-documenten-en-bundelen"},
 "title": {"en": "How does the 55-document limit work — and should we combine documents into one?",
           "fr": "Comment fonctionne la limite de 55 documents — et faut-il regrouper des documents en un seul ?",
           "nl": "Hoe werkt de limiet van 55 documenten — en moet u documenten bundelen in één bestand?"},
 "summary": {"en": "The 55-document limit applies per assessment cycle, not cumulatively: previously submitted documents stay in the Document Library and can be reattached without consuming the new quota. Best practice remains separate, distinct uploads rather than merged files.",
             "fr": "La limite de 55 documents s'applique par cycle d'évaluation, pas en cumulé : les documents déjà soumis restent dans la bibliothèque et peuvent être rattachés sans consommer le nouveau quota. La bonne pratique reste des documents distincts plutôt que des fichiers fusionnés.",
             "nl": "De limiet van 55 documenten geldt per beoordelingscyclus, niet cumulatief: eerder ingediende documenten blijven in de documentbibliotheek en kunnen opnieuw worden gekoppeld zonder het nieuwe quotum te verbruiken. De beste praktijk blijft aparte documenten in plaats van samengevoegde bestanden."},
 "body": {
  "en": """While the EcoVadis methodology now permits some document consolidation, the best practice remains to upload **separate documents**. EcoVadis allows up to 55 documents per assessment, so keeping them distinct enhances clarity and reviewer accessibility. Retaining older valid documents alongside new versions to demonstrate year-on-year progress is encouraged.

The limit applies **per assessment cycle, not cumulatively**. Each time a new questionnaire is opened, you receive a fresh 55-document allowance for newly uploaded files. All documents submitted in previous assessments remain accessible in the Document Library and can be **reattached to questions in the new cycle without consuming any of the quota** — only fresh uploads count. The practical implication: where strong evidence already exists from the previous assessment, reattaching it is almost always the right approach; reserve new uploads for evidence that has changed, improved, or is being submitted for the first time.""",
  "fr": """La méthodologie EcoVadis permet désormais une certaine consolidation, mais la bonne pratique reste de charger des **documents séparés**. EcoVadis accepte jusqu'à 55 documents par évaluation : les garder distincts améliore la clarté et l'accessibilité pour l'analyste. Conserver les anciens documents valides à côté des nouvelles versions est encouragé — cela démontre la progression d'année en année.

La limite s'applique **par cycle d'évaluation, pas en cumulé**. À chaque nouvelle ouverture de questionnaire, vous recevez un nouveau quota de 55 documents pour les fichiers fraîchement chargés. Tous les documents soumis lors des évaluations précédentes restent accessibles dans la bibliothèque de documents et peuvent être **rattachés aux questions du nouveau cycle sans consommer le quota** — seuls les nouveaux chargements comptent. Implication pratique : quand une preuve solide existe déjà du cycle précédent, la rattacher est presque toujours le bon réflexe ; réservez les nouveaux chargements aux preuves qui ont changé, se sont améliorées ou sont soumises pour la première fois.""",
  "nl": """De EcoVadis-methodologie laat nu enige consolidatie toe, maar de beste praktijk blijft **aparte documenten** opladen. EcoVadis aanvaardt tot 55 documenten per beoordeling: ze apart houden verhoogt de duidelijkheid en de toegankelijkheid voor de analist. Oudere geldige documenten naast de nieuwe versies bewaren wordt aangemoedigd — het toont de vooruitgang van jaar tot jaar.

De limiet geldt **per beoordelingscyclus, niet cumulatief**. Bij elke nieuwe vragenlijst krijgt u een vers quotum van 55 documenten voor nieuw opgeladen bestanden. Alle documenten uit vorige beoordelingen blijven toegankelijk in de documentbibliotheek en kunnen **aan de vragen van de nieuwe cyclus worden gekoppeld zonder het quotum te verbruiken** — alleen nieuwe uploads tellen. Praktisch gevolg: waar sterk bewijs uit de vorige beoordeling al bestaat, is opnieuw koppelen bijna altijd de juiste keuze; reserveer nieuwe uploads voor bewijs dat veranderd of verbeterd is, of voor het eerst wordt ingediend."""},
 "content_kind": "methodology",
 "topics": ["questionnaire", "preuves", "plateforme"],
 "keywords": {"en": ["55 document limit", "EcoVadis document library", "combine documents", "reattach documents"],
              "fr": ["limite 55 documents", "bibliothèque de documents EcoVadis", "regrouper documents", "rattacher documents"],
              "nl": ["limiet 55 documenten", "documentbibliotheek EcoVadis", "documenten bundelen", "documenten opnieuw koppelen"]},
 "source_note": SRC25 + " + " + SRC26_2,
 "related": ["build-strong-ecovadis-submissions-consistently", "supporting-documents-for-xs-companies"],
},
{
 "id": "kb-0101",
 "slug": {"en": "how-ecovadis-ensures-fair-scoring",
          "fr": "comment-ecovadis-garantit-une-notation-equitable",
          "nl": "hoe-ecovadis-eerlijke-scoring-garandeert"},
 "title": {"en": "How does EcoVadis ensure a fair scoring system across diverse companies and sectors?",
           "fr": "Comment EcoVadis garantit-il une notation équitable entre entreprises et secteurs différents ?",
           "nl": "Hoe garandeert EcoVadis een eerlijke scoring over verschillende ondernemingen en sectoren?"},
 "summary": {"en": "Questionnaires are tailored to company size, industry and geography, activating only relevant indicators, so smaller firms are not judged on criteria meant for large groups; medals reflect percentile ranks across all rated companies worldwide.",
             "fr": "Les questionnaires sont adaptés à la taille, au secteur et à la géographie, n'activant que les indicateurs pertinents ; les médailles reflètent le rang percentile parmi toutes les entreprises évaluées dans le monde.",
             "nl": "De vragenlijsten zijn op maat van grootte, sector en geografie en activeren alleen relevante indicatoren; medailles weerspiegelen het percentiel tegenover alle beoordeelde ondernemingen wereldwijd."},
 "body": {
  "en": """EcoVadis designs questionnaires tailored to company size, industry and geography, **activating only the relevant indicators**. This ensures that medium and smaller enterprises are not penalised for criteria meant for larger firms. Scores reflect **percentile ranks across all participants**: a Gold medal signifies top-5% performance against all assessed companies worldwide, which is precisely what motivates continuous improvement — the peer group keeps getting better.""",
  "fr": """EcoVadis conçoit des questionnaires adaptés à la taille, au secteur et à la géographie de l'entreprise, en **n'activant que les indicateurs pertinents**. Les moyennes et petites entreprises ne sont donc pas pénalisées par des critères pensés pour les grands groupes. Les scores reflètent le **rang percentile parmi tous les participants** : une médaille d'Or signifie une performance dans le top 5 % de toutes les entreprises évaluées dans le monde — ce qui pousse à l'amélioration continue, car le groupe de comparaison progresse en permanence.""",
  "nl": """EcoVadis ontwerpt vragenlijsten op maat van grootte, sector en geografie, en **activeert alleen de relevante indicatoren**. Middelgrote en kleinere ondernemingen worden dus niet bestraft voor criteria die voor grote groepen zijn bedoeld. De scores weerspiegelen het **percentiel tegenover alle deelnemers**: een Gouden medaille betekent een prestatie in de top 5% van alle beoordeelde ondernemingen wereldwijd — wat aanzet tot continue verbetering, want de vergelijkingsgroep gaat voortdurend vooruit."""},
 "content_kind": "methodology",
 "topics": ["methodologie", "medailles-percentiles"],
 "keywords": {"en": ["fair scoring", "tailored questionnaire", "activated indicators", "percentile ranking"],
              "fr": ["notation équitable", "questionnaire adapté", "indicateurs activés", "classement percentile"],
              "nl": ["eerlijke scoring", "vragenlijst op maat", "geactiveerde indicatoren", "percentielrangschikking"]},
 "source_note": SRC25,
 "related": ["ecovadis-activated-criteria-by-sector", "understanding-the-ecovadis-scorecard"],
},
{
 "id": "kb-0102",
 "slug": {"en": "motivating-procurement-teams-sustainability",
          "fr": "motiver-les-equipes-achats-durabilite",
          "nl": "inkoopteams-motiveren-voor-duurzaamheid"},
 "title": {"en": "How can procurement teams be motivated to integrate sustainability into their processes?",
           "fr": "Comment motiver les équipes achats à intégrer la durabilité dans leurs processus ?",
           "nl": "Hoe motiveert u inkoopteams om duurzaamheid in hun processen te integreren?"},
 "summary": {"en": "Link ESG objectives into procurement KPIs and decision cycles through governance, secure leadership endorsement, foster collaboration across supply chain, HR and sustainability teams, and offer training that clarifies sustainable procurement.",
             "fr": "Relier les objectifs ESG aux KPI achats et aux cycles de décision via la gouvernance, obtenir l'appui de la direction, faire collaborer les équipes, et former les acheteurs aux achats responsables.",
             "nl": "Koppel ESG-doelstellingen aan inkoop-KPI's en beslissingscycli via governance, verzeker de steun van de directie, laat teams samenwerken en bied opleiding aan die duurzame inkoop verduidelijkt."},
 "body": {
  "en": """Effective procurement engagement requires **governance structures that link ESG objectives into KPIs and decision-making cycles**. Collaboration across supply chain, HR and sustainability teams — alongside leadership endorsement — is critical. Training modules that clarify what sustainable procurement means in practice, and that encourage pragmatic supplier engagement, help embed sustainability in day-to-day procurement practices rather than leaving it as a parallel initiative.""",
  "fr": """Un engagement achats efficace exige des **structures de gouvernance qui relient les objectifs ESG aux KPI et aux cycles de décision**. La collaboration entre les équipes supply chain, RH et durabilité — avec l'appui de la direction — est critique. Des modules de formation qui clarifient ce que signifient concrètement les achats responsables, et qui encouragent un engagement fournisseurs pragmatique, ancrent la durabilité dans les pratiques d'achat quotidiennes au lieu d'en faire une initiative parallèle.""",
  "nl": """Een doeltreffend engagement van de inkoop vereist **governancestructuren die ESG-doelstellingen koppelen aan KPI's en beslissingscycli**. Samenwerking tussen de teams supply chain, hr en duurzaamheid — met de steun van de directie — is cruciaal. Opleidingsmodules die verduidelijken wat duurzame inkoop concreet betekent en die een pragmatisch leveranciersengagement aanmoedigen, verankeren duurzaamheid in de dagelijkse inkooppraktijk in plaats van er een parallel initiatief van te maken."""},
 "content_kind": "methodology",
 "themes": ["sustainable-procurement"],
 "topics": ["achats-responsables"],
 "keywords": {"en": ["procurement engagement", "ESG KPIs", "buyer training", "governance"],
              "fr": ["engagement achats", "KPI ESG", "formation acheteurs", "gouvernance"],
              "nl": ["inkoopengagement", "ESG-KPI's", "opleiding inkopers", "governance"]},
 "source_note": SRC25,
 "related": ["sustainable-procurement-where-to-start", "ecovadis-supplier-engagement-programmes"],
},
{
 "id": "kb-0103",
 "slug": {"en": "handling-multiple-customer-questionnaires",
          "fr": "gerer-les-questionnaires-clients-multiples",
          "nl": "omgaan-met-meerdere-klantenvragenlijsten"},
 "title": {"en": "How can we manage varied sustainability questionnaires from customers when already rated by EcoVadis?",
           "fr": "Comment gérer les questionnaires de durabilité variés de nos clients quand nous sommes déjà notés EcoVadis ?",
           "nl": "Hoe beheert u uiteenlopende duurzaamheidsvragenlijsten van klanten als u al een EcoVadis-score hebt?"},
 "summary": {"en": "Prompt customers to consult your EcoVadis scorecard instead of sending their own questionnaires: positioning the platform as the single source of supplier sustainability data reduces survey fatigue and the burden of repetitive requests.",
             "fr": "Invitez vos clients à consulter votre fiche d'évaluation (scorecard) EcoVadis plutôt que d'envoyer leurs propres questionnaires : la plateforme comme source unique réduit la fatigue d'enquête.",
             "nl": "Vraag uw klanten uw EcoVadis-scorecard te raadplegen in plaats van eigen vragenlijsten te sturen: het platform als unieke bron vermindert de enquêtemoeheid."},
 "body": {
  "en": """Prompt customers to **consult your EcoVadis scorecard** to avoid duplicate requests. Survey fatigue is common, and better internal alignment within customer organisations can reduce repetitive questionnaires. Leveraging the EcoVadis platform as a **single source of supplier sustainability data** streamlines communication and reduces the burden on you as a supplier — one structured, verified scorecard replaces a stack of divergent Excel questionnaires.""",
  "fr": """Invitez vos clients à **consulter votre fiche d'évaluation (scorecard) EcoVadis** pour éviter les demandes en double. La fatigue d'enquête est réelle, et un meilleur alignement interne chez vos clients réduit les questionnaires répétitifs. Faire de la plateforme EcoVadis la **source unique des données de durabilité fournisseurs** fluidifie la communication et allège votre charge : une fiche d'évaluation structurée et vérifiée remplace une pile de questionnaires Excel divergents.""",
  "nl": """Vraag uw klanten uw **EcoVadis-scorecard te raadplegen** om dubbele verzoeken te vermijden. Enquêtemoeheid is reëel, en een betere interne afstemming bij uw klanten vermindert de repetitieve vragenlijsten. Het EcoVadis-platform inzetten als **unieke bron van duurzaamheidsdata over leveranciers** stroomlijnt de communicatie en verlicht uw last: één gestructureerde, geverifieerde scorecard vervangt een stapel uiteenlopende Excel-vragenlijsten."""},
 "content_kind": "general",
 "topics": ["plateforme", "donneur-d-ordres"],
 "keywords": {"en": ["survey fatigue", "share scorecard", "customer questionnaires", "single source"],
              "fr": ["fatigue d'enquête", "partager la scorecard", "questionnaires clients", "source unique"],
              "nl": ["enquêtemoeheid", "scorecard delen", "klantenvragenlijsten", "unieke bron"]},
 "source_note": SRC25,
 "related": ["read-share-maximise-your-ecovadis-scorecard"],
},
{
 "id": "kb-0104",
 "slug": {"en": "vsme-and-ecovadis-complementary",
          "fr": "vsme-et-ecovadis-complementaires",
          "nl": "vsme-en-ecovadis-complementair"},
 "title": {"en": "Is VSME reporting necessary for a company already rated by EcoVadis — and what score can it unlock?",
           "fr": "Le reporting VSME est-il nécessaire pour une entreprise déjà notée EcoVadis — et quel score peut-il débloquer ?",
           "nl": "Is VSME-rapportering nodig voor een onderneming die al een EcoVadis-score heeft — en welke score kan ze ontgrendelen?"},
 "summary": {"en": "EcoVadis rates sustainability management; VSME is a structured ESG reporting framework — they complement each other. VSME is formally recognised by EcoVadis: the Basic Module unlocks up to 75/100 on the Reporting indicator, Basic + Comprehensive with third-party assurance up to 100/100.",
             "fr": "EcoVadis note le système de gestion ; la VSME est un cadre de reporting structuré — ils se complètent. La VSME est reconnue par EcoVadis : le module Basic débloque jusqu'à 75/100 en Reporting, Basic + Comprehensive avec vérification tierce jusqu'à 100/100.",
             "nl": "EcoVadis scoort het managementsysteem; VSME is een gestructureerd rapporteringskader — ze vullen elkaar aan. VSME is erkend door EcoVadis: de Basic-module ontgrendelt tot 75/100 op Rapportering, Basic + Comprehensive met externe verificatie tot 100/100."},
 "body": {
  "en": """They complement rather than replace each other. **EcoVadis rates sustainability management**, while **VSME offers a structured ESG reporting framework** (the Voluntary SME Standard developed by EFRAG, based on ESRS). Companies can use VSME to satisfy external reporting demands from customers and regulators, while EcoVadis validates internal governance practices — a comprehensive ESG approach tuned to stakeholder demands.

On scoring: VSME is **fully recognised by EcoVadis as a valid reporting framework for any company size**. The maximum achievable depends on the module: **VSME Basic Module only → up to 75/100** on the Reporting indicator; **Basic + Comprehensive Module → up to 100/100, subject to third-party assurance**. Note that EcoVadis does not audit whether your VSME report meets VSME's own standards — it assesses whether the report contains the specific disclosures and KPIs its scoring levels require: a sustainability or annual report, a declared alignment with a recognised standard, a (double) materiality analysis, and third-party verification for the top score.""",
  "fr": """Ils se complètent plutôt qu'ils ne se remplacent. **EcoVadis note le système de gestion de la durabilité**, tandis que la **VSME offre un cadre de reporting ESG structuré** (le standard volontaire PME développé par l'EFRAG, basé sur les ESRS). Une entreprise peut utiliser la VSME pour répondre aux demandes de reporting externes des clients et régulateurs, pendant qu'EcoVadis valide ses pratiques de gouvernance internes — une approche ESG complète, accordée aux attentes des parties prenantes.

Côté score : la VSME est **pleinement reconnue par EcoVadis comme cadre de reporting valide, quelle que soit la taille**. Le maximum atteignable dépend du module : **module Basic seul → jusqu'à 75/100** en Reporting ; **Basic + Comprehensive → jusqu'à 100/100, sous réserve d'une vérification tierce**. À noter : EcoVadis n'audite pas la conformité de votre rapport aux standards VSME eux-mêmes — il vérifie que le rapport contient les divulgations et KPI exigés par ses niveaux de score : un rapport de durabilité ou annuel, un alignement déclaré sur un standard reconnu, une analyse de (double) matérialité, et la vérification tierce pour le score maximal.""",
  "nl": """Ze vullen elkaar aan in plaats van elkaar te vervangen. **EcoVadis scoort het duurzaamheidsmanagementsysteem**, terwijl **VSME een gestructureerd ESG-rapporteringskader biedt** (de vrijwillige kmo-standaard van EFRAG, gebaseerd op de ESRS). Een onderneming kan VSME gebruiken voor de externe rapporteringsvragen van klanten en regelgevers, terwijl EcoVadis de interne governancepraktijken valideert — een volledige ESG-aanpak, afgestemd op de verwachtingen van de stakeholders.

Qua score: VSME is **volledig erkend door EcoVadis als geldig rapporteringskader, ongeacht de grootte**. Het haalbare maximum hangt af van de module: **alleen Basic-module → tot 75/100** op de indicator Rapportering; **Basic + Comprehensive → tot 100/100, mits externe verificatie**. Let op: EcoVadis auditeert niet of uw rapport aan de VSME-normen zelf voldoet — het controleert of het rapport de vereiste toelichtingen en KPI's bevat: een duurzaamheids- of jaarverslag, een verklaarde afstemming op een erkende standaard, een (dubbele) materialiteitsanalyse, en externe verificatie voor de topscore."""},
 "content_kind": "reporting",
 "topics": ["vsme-csrd", "methodologie"],
 "keywords": {"en": ["VSME EcoVadis", "Reporting indicator 75", "Basic Module", "Comprehensive Module", "third-party assurance"],
              "fr": ["VSME EcoVadis", "Reporting 75", "module Basic", "module Comprehensive", "vérification tierce"],
              "nl": ["VSME EcoVadis", "Rapportering 75", "Basic-module", "Comprehensive-module", "externe verificatie"]},
 "source_note": SRC25 + " + " + SRC26_2,
 "related": ["whats-changing-in-2026", "ecovadis-rising-standards-2026"],
},
{
 "id": "kb-0105",
 "slug": {"en": "what-is-double-materiality",
          "fr": "quest-ce-que-la-double-materialite",
          "nl": "wat-is-dubbele-materialiteit"},
 "title": {"en": "What is double materiality and why is it central to CSRD-aligned reporting?",
           "fr": "Qu'est-ce que la double matérialité et pourquoi est-elle centrale dans le reporting aligné CSRD ?",
           "nl": "Wat is dubbele materialiteit en waarom is ze centraal in CSRD-conforme rapportering?"},
 "summary": {"en": "Double materiality assesses both how sustainability issues impact the company financially and how the company impacts the environment and society; this dual lens drives prioritisation and disclosures under CSRD.",
             "fr": "La double matérialité évalue à la fois l'impact financier des enjeux de durabilité sur l'entreprise et l'impact de l'entreprise sur l'environnement et la société ; cette double lecture pilote la priorisation et les divulgations CSRD.",
             "nl": "Dubbele materialiteit beoordeelt zowel hoe duurzaamheidskwesties de onderneming financieel raken als hoe de onderneming het milieu en de samenleving beïnvloedt; die dubbele lens stuurt de prioritering en de CSRD-rapportering."},
 "body": {
  "en": """Double materiality assesses **both how sustainability impacts the company financially and how the company impacts the environment and society**. This holistic lens shapes prioritisation and disclosures under the CSRD, ensuring companies report on all material ESG risks and opportunities affecting financial and non-financial stakeholders. It is also the most credible foundation for the EcoVadis materiality customisation pilot and for justifying which topics are — and are not — material to your operations.""",
  "fr": """La double matérialité évalue **à la fois l'impact financier des enjeux de durabilité sur l'entreprise et l'impact de l'entreprise sur l'environnement et la société**. Cette lecture globale structure la priorisation et les divulgations sous la CSRD : l'entreprise rapporte tous les risques et opportunités ESG matériels pour ses parties prenantes financières et non financières. C'est aussi la base la plus crédible pour le pilote de personnalisation de la matérialité d'EcoVadis et pour justifier quels sujets sont — ou ne sont pas — matériels pour vos opérations.""",
  "nl": """Dubbele materialiteit beoordeelt **zowel hoe duurzaamheid de onderneming financieel raakt als hoe de onderneming het milieu en de samenleving beïnvloedt**. Die holistische lens structureert de prioritering en de rapportering onder de CSRD: de onderneming rapporteert alle materiële ESG-risico's en -kansen voor haar financiële en niet-financiële stakeholders. Het is ook de meest geloofwaardige basis voor het materialiteitspilootproject van EcoVadis en om te verantwoorden welke onderwerpen wel — en niet — materieel zijn voor uw activiteiten."""},
 "content_kind": "reporting",
 "topics": ["vsme-csrd", "methodologie"],
 "keywords": {"en": ["double materiality", "CSRD", "materiality assessment", "ESG disclosures"],
              "fr": ["double matérialité", "CSRD", "analyse de matérialité", "divulgations ESG"],
              "nl": ["dubbele materialiteit", "CSRD", "materialiteitsanalyse", "ESG-rapportering"]},
 "source_note": SRC25,
 "related": ["whats-changing-in-2026"],
},
{
 "id": "kb-0106",
 "slug": {"en": "how-often-refresh-double-materiality",
          "fr": "frequence-actualisation-double-materialite",
          "nl": "hoe-vaak-dubbele-materialiteit-actualiseren"},
 "title": {"en": "How often should companies refresh their double materiality assessment?",
           "fr": "À quelle fréquence actualiser son analyse de double matérialité ?",
           "nl": "Hoe vaak moet u uw dubbele-materialiteitsanalyse actualiseren?"},
 "summary": {"en": "DMAs should be updated regularly and thoroughly documented: auditors review stakeholder selection, threshold-setting and the treatment of negative human-rights impacts, and transparent, evolving assessments pass assurance more smoothly.",
             "fr": "L'analyse doit être actualisée régulièrement et documentée en profondeur : les auditeurs examinent la sélection des parties prenantes, les seuils et le traitement des impacts négatifs sur les droits humains.",
             "nl": "De analyse moet regelmatig worden geactualiseerd en grondig gedocumenteerd: auditors bekijken de stakeholderselectie, de drempels en de behandeling van negatieve mensenrechtenimpacts."},
 "body": {
  "en": """Double materiality assessments should be **updated regularly and thoroughly documented**. Auditors often review DMA processes to verify stakeholder selection, threshold-setting, and the treatment of negative human-rights impacts. Companies that incorporate insights transparently and demonstrate an evolving understanding of their material topics tend to have smoother assurance processes — a static, one-off DMA is a red flag.""",
  "fr": """L'analyse de double matérialité doit être **actualisée régulièrement et documentée en profondeur**. Les auditeurs examinent souvent le processus : sélection des parties prenantes, fixation des seuils, traitement des impacts négatifs sur les droits humains. Les entreprises qui intègrent les enseignements de façon transparente et démontrent une compréhension évolutive de leurs sujets matériels traversent l'assurance plus facilement — une DMA statique et ponctuelle est un signal d'alerte.""",
  "nl": """De dubbele-materialiteitsanalyse moet **regelmatig worden geactualiseerd en grondig gedocumenteerd**. Auditors bekijken vaak het proces: de selectie van stakeholders, de drempelbepaling en de behandeling van negatieve mensenrechtenimpacts. Ondernemingen die inzichten transparant verwerken en een evoluerend begrip van hun materiële onderwerpen aantonen, doorlopen de assurance vlotter — een statische, eenmalige analyse is een alarmsignaal."""},
 "content_kind": "reporting",
 "topics": ["vsme-csrd", "methodologie"],
 "keywords": {"en": ["DMA refresh", "materiality update", "assurance", "stakeholder engagement"],
              "fr": ["actualisation DMA", "mise à jour matérialité", "assurance", "parties prenantes"],
              "nl": ["DMA-actualisering", "materialiteitsupdate", "assurance", "stakeholders"]},
 "source_note": SRC25,
 "related": ["whats-changing-in-2026"],
},
{
 "id": "kb-0107",
 "slug": {"en": "importance-of-peer-benchmarking-esg",
          "fr": "importance-du-benchmark-esg",
          "nl": "belang-van-esg-benchmarking"},
 "title": {"en": "How important is peer benchmarking when developing an ESG strategy?",
           "fr": "Quelle importance donner au benchmark des pairs dans une stratégie ESG ?",
           "nl": "Hoe belangrijk is benchmarking met sectorgenoten bij het ontwikkelen van een ESG-strategie?"},
 "summary": {"en": "Benchmarking against peers and understanding customer expectations are crucial to stay competitive: knowing the ESG landscape of competitors enables better strategic alignment while initiatives stay tailored to your own maturity.",
             "fr": "Se comparer aux pairs et comprendre les attentes clients est crucial pour rester compétitif : connaître le paysage ESG des concurrents permet un meilleur alignement stratégique.",
             "nl": "Vergelijken met sectorgenoten en de klantverwachtingen begrijpen is cruciaal om competitief te blijven: het ESG-landschap van concurrenten kennen zorgt voor een betere strategische afstemming."},
 "body": {
  "en": """Benchmarking against peers and understanding customer expectations are **crucial to staying competitive**. While companies rightly tailor initiatives to their own business model and maturity, knowing the ESG landscape of competitors enables better strategic alignment and addresses stakeholder demands more effectively. In the EcoVadis context this is doubly true: since medals are percentile-based, your position is literally defined relative to your peers.""",
  "fr": """Se comparer aux pairs et comprendre les attentes des clients est **crucial pour rester compétitif**. Chaque entreprise adapte à juste titre ses initiatives à son modèle d'affaires et à sa maturité, mais connaître le paysage ESG de ses concurrents permet un meilleur alignement stratégique et une réponse plus efficace aux attentes des parties prenantes. Dans le contexte EcoVadis, c'est doublement vrai : les médailles étant basées sur le percentile, votre position est littéralement définie par rapport à vos pairs.""",
  "nl": """Vergelijken met sectorgenoten en de klantverwachtingen begrijpen is **cruciaal om competitief te blijven**. Elke onderneming stemt haar initiatieven terecht af op haar eigen model en maturiteit, maar het ESG-landschap van de concurrenten kennen zorgt voor een betere strategische afstemming en een doeltreffender antwoord op de stakeholderverwachtingen. In de EcoVadis-context geldt dat dubbel: medailles zijn percentielgebaseerd, dus uw positie wordt letterlijk bepaald tegenover uw sectorgenoten."""},
 "content_kind": "general",
 "topics": ["methodologie", "medailles-percentiles"],
 "keywords": {"en": ["peer benchmarking", "ESG strategy", "competitive position"],
              "fr": ["benchmark pairs", "stratégie ESG", "position concurrentielle"],
              "nl": ["benchmarking sectorgenoten", "ESG-strategie", "concurrentiepositie"]},
 "source_note": SRC25,
 "related": ["ecovadis-rising-standards-2026", "ecovadis-thresholds-belgian-packaging-pharma"],
},
{
 "id": "kb-0108",
 "slug": {"en": "employee-engagement-emissions-monitoring",
          "fr": "engager-les-employes-suivi-des-emissions",
          "nl": "medewerkers-betrekken-bij-emissiemonitoring"},
 "title": {"en": "What practical steps can cultivate employee engagement in emissions monitoring?",
           "fr": "Quelles étapes pratiques pour engager les employés dans le suivi des émissions ?",
           "nl": "Welke praktische stappen bevorderen de betrokkenheid van medewerkers bij emissiemonitoring?"},
 "summary": {"en": "Communication and education underpin cultural change: embed carbon goals in strategy and leadership communication, assign accountability, use sustainability task forces, and start measuring Scope 1 and 2 incrementally even in small firms.",
             "fr": "Communication et éducation fondent le changement culturel : ancrer les objectifs carbone dans la stratégie, attribuer la responsabilité, créer des task forces, et commencer à mesurer les Scopes 1 et 2 progressivement.",
             "nl": "Communicatie en educatie dragen de cultuurverandering: veranker koolstofdoelen in de strategie, wijs verantwoordelijkheid toe, richt taskforces op en begin Scope 1 en 2 stapsgewijs te meten."},
 "body": {
  "en": """Communication and education underpin cultural change. Organisations should **embed carbon-reduction goals in strategy and leadership communication, assign accountability**, and use tools such as sustainability task forces. Even small firms can begin measuring Scope 1 and 2 emissions incrementally to build awareness and data maturity — the act of measuring is itself an engagement lever.""",
  "fr": """La communication et l'éducation fondent le changement culturel. L'organisation doit **ancrer les objectifs de réduction carbone dans la stratégie et la communication de la direction, attribuer la responsabilité**, et utiliser des outils comme les task forces durabilité. Même une petite entreprise peut commencer à mesurer ses émissions Scopes 1 et 2 progressivement pour bâtir la sensibilisation et la maturité des données — l'acte de mesurer est en soi un levier d'engagement.""",
  "nl": """Communicatie en educatie dragen de cultuurverandering. De organisatie moet **de koolstofreductiedoelen verankeren in de strategie en de communicatie van de directie, verantwoordelijkheid toewijzen**, en instrumenten inzetten zoals duurzaamheidstaskforces. Zelfs een kleine onderneming kan haar Scope 1- en 2-emissies stapsgewijs beginnen meten om bewustzijn en datamaturiteit op te bouwen — het meten zelf is al een engagementshefboom."""},
 "content_kind": "methodology",
 "themes": ["environment"],
 "topics": ["carbone-ghg"],
 "keywords": {"en": ["employee engagement", "emissions monitoring", "carbon culture", "task force"],
              "fr": ["engagement employés", "suivi des émissions", "culture carbone", "task force"],
              "nl": ["medewerkersbetrokkenheid", "emissiemonitoring", "koolstofcultuur", "taskforce"]},
 "source_note": SRC25,
 "related": ["ecovadis-and-ghg-baseline", "environmental-indicators-to-collect"],
},
{
 "id": "kb-0109",
 "slug": {"en": "why-scope-3-despite-double-counting",
          "fr": "pourquoi-le-scope-3-malgre-le-double-comptage",
          "nl": "waarom-scope-3-ondanks-dubbeltelling"},
 "title": {"en": "Why is Scope 3 supplier emission reporting necessary despite perceived double counting?",
           "fr": "Pourquoi le reporting Scope 3 est-il nécessaire malgré le double comptage apparent ?",
           "nl": "Waarom is Scope 3-rapportering nodig ondanks de schijnbare dubbeltelling?"},
 "summary": {"en": "Scope 3 assigns responsibility to buyers for their supply-chain emissions because procurement decisions influence upstream emissions; counted at multiple tiers, it drives collective action through supplier engagement and greener purchasing.",
             "fr": "Le Scope 3 attribue aux acheteurs la responsabilité des émissions de leur chaîne, car les décisions d'achat influencent l'amont ; compté à plusieurs niveaux, il pousse l'action collective.",
             "nl": "Scope 3 legt de verantwoordelijkheid voor ketenemissies bij de kopers, want inkoopbeslissingen beïnvloeden de stroomopwaartse emissies; op meerdere niveaus geteld, drijft het collectieve actie aan."},
 "body": {
  "en": """Scope 3 reporting **assigns responsibility to buyers for their supply-chain emissions**, since procurement decisions directly influence upstream emissions. Though the same tonne of CO₂ is counted multiple times at different corporate tiers, Scope 3 drives collective action to lower global emissions through informed supplier engagement and greener purchasing choices. The double counting is a feature of the accountability model, not a flaw in the accounting.""",
  "fr": """Le reporting Scope 3 **attribue aux acheteurs la responsabilité des émissions de leur chaîne d'approvisionnement**, car les décisions d'achat influencent directement les émissions en amont. La même tonne de CO₂ est certes comptée plusieurs fois à différents niveaux, mais le Scope 3 pousse à l'action collective — engagement fournisseurs informé et choix d'achats plus verts. Le double comptage est une caractéristique du modèle de responsabilité, pas un défaut de comptabilité.""",
  "nl": """Scope 3-rapportering **legt de verantwoordelijkheid voor de ketenemissies bij de kopers**, omdat inkoopbeslissingen de stroomopwaartse emissies rechtstreeks beïnvloeden. Dezelfde ton CO₂ wordt weliswaar meermaals geteld op verschillende niveaus, maar Scope 3 drijft collectieve actie aan — geïnformeerd leveranciersengagement en groenere aankoopkeuzes. De dubbeltelling is een kenmerk van het verantwoordelijkheidsmodel, geen boekhoudkundige fout."""},
 "content_kind": "methodology",
 "themes": ["environment"],
 "topics": ["carbone-ghg", "achats-responsables"],
 "keywords": {"en": ["Scope 3", "double counting", "supply chain emissions", "Category 1"],
              "fr": ["Scope 3", "double comptage", "émissions chaîne d'approvisionnement", "catégorie 1"],
              "nl": ["Scope 3", "dubbeltelling", "ketenemissies", "categorie 1"]},
 "source_note": SRC25,
 "related": ["ecovadis-and-ghg-baseline", "ecovadis-supplier-engagement-programmes"],
},
{
 "id": "kb-0110",
 "slug": {"en": "carbon-target-setting-and-sbti",
          "fr": "fixer-des-objectifs-carbone-et-sbti",
          "nl": "koolstofdoelen-stellen-en-sbti"},
 "title": {"en": "How should companies approach carbon target setting, especially SBTi commitments?",
           "fr": "Comment aborder la fixation d'objectifs carbone, notamment les engagements SBTi ?",
           "nl": "Hoe pakt u het stellen van koolstofdoelen aan, in het bijzonder SBTi-engagementen?"},
 "summary": {"en": "Science-based targets signal ambition, integrity and leadership to investors and customers; the emphasis should be on credible baselining and progressively ambitious commitments rather than hesitating over achievability.",
             "fr": "Les objectifs science-based signalent ambition, intégrité et leadership ; l'accent doit porter sur une base de référence crédible et des engagements progressivement ambitieux.",
             "nl": "Science-based doelen signaleren ambitie, integriteit en leiderschap; de nadruk moet liggen op een geloofwaardige nulmeting en progressief ambitieuze engagementen."},
 "body": {
  "en": """Setting science-based targets **signals ambition, integrity and leadership** to investors and customers. Some firms hesitate over achievability, but SBTi targets help organisations clarify reduction pathways and gain stakeholder trust. The emphasis should be on **credible baselining and progressively ambitious commitments** — a defensible starting inventory matters more than a spectacular headline number. In EcoVadis terms, a validated science-based target is high-quality evidence of a quantitative GHG commitment.""",
  "fr": """Fixer des objectifs science-based **signale l'ambition, l'intégrité et le leadership** aux investisseurs et aux clients. Certaines entreprises hésitent sur l'atteignabilité, mais les objectifs SBTi aident à clarifier les trajectoires de réduction et à gagner la confiance des parties prenantes. L'accent doit porter sur **une base de référence crédible et des engagements progressivement ambitieux** — un inventaire de départ défendable compte plus qu'un chiffre spectaculaire. En termes EcoVadis, un objectif science-based validé est une preuve de haute qualité d'engagement GES quantitatif.""",
  "nl": """Science-based doelen stellen **signaleert ambitie, integriteit en leiderschap** aan investeerders en klanten. Sommige ondernemingen twijfelen over de haalbaarheid, maar SBTi-doelen helpen reductiepaden te verduidelijken en het vertrouwen van stakeholders te winnen. De nadruk moet liggen op **een geloofwaardige nulmeting en progressief ambitieuze engagementen** — een verdedigbare startinventaris telt meer dan een spectaculair cijfer. In EcoVadis-termen is een gevalideerd science-based doel bewijs van hoge kwaliteit voor een kwantitatief broeikasgasengagement."""},
 "content_kind": "methodology",
 "themes": ["environment"],
 "topics": ["carbone-ghg"],
 "keywords": {"en": ["SBTi", "science-based targets", "carbon targets", "baseline"],
              "fr": ["SBTi", "objectifs science-based", "objectifs carbone", "base de référence"],
              "nl": ["SBTi", "science-based doelen", "koolstofdoelen", "nulmeting"]},
 "source_note": SRC25,
 "related": ["ecovadis-and-ghg-baseline"],
},
{
 "id": "kb-0111",
 "slug": {"en": "climate-risk-assessments-and-monitoring",
          "fr": "analyses-de-risque-climatique-et-suivi",
          "nl": "klimaatrisicoanalyses-en-monitoring"},
 "title": {"en": "What role do risk assessments and monitoring systems play in climate resilience?",
           "fr": "Quel rôle jouent les analyses de risque et les systèmes de suivi dans la résilience climatique ?",
           "nl": "Welke rol spelen risicoanalyses en monitoringsystemen in klimaatveerkracht?"},
 "summary": {"en": "Companies need to integrate climate risk analysis and emissions data in an iterative monitoring system; sector-specific protocols guide the focus on transitional and physical risks, supporting investment decisions, compliance and resilience planning.",
             "fr": "Il faut intégrer l'analyse des risques climatiques et les données d'émissions dans un système de suivi itératif ; les protocoles sectoriels orientent le focus sur les risques de transition et physiques.",
             "nl": "Integreer klimaatrisicoanalyse en emissiedata in een iteratief monitoringsysteem; sectorspecifieke protocollen sturen de focus op transitie- en fysieke risico's."},
 "body": {
  "en": """Companies need to integrate **climate risk analysis and emissions data in an iterative monitoring system**. Sector-specific protocols — especially in finance and insurance — guide the focus on transitional and physical risks. Such systems support better investment decisions, compliance, and resilience planning. For EcoVadis, documented external climate-risk assessment also feeds specific Environment questions (see the ENV7003/ENV7012 articles).""",
  "fr": """L'entreprise doit intégrer **l'analyse des risques climatiques et les données d'émissions dans un système de suivi itératif**. Les protocoles sectoriels — surtout en finance et assurance — orientent le focus sur les risques de transition et les risques physiques. Ces systèmes soutiennent de meilleures décisions d'investissement, la conformité et la planification de la résilience. Pour EcoVadis, une évaluation documentée des risques climatiques externes alimente aussi des questions Environnement spécifiques (voir les fiches ENV7003/ENV7012).""",
  "nl": """De onderneming moet **klimaatrisicoanalyse en emissiedata integreren in een iteratief monitoringsysteem**. Sectorspecifieke protocollen — vooral in financiën en verzekeringen — sturen de focus op transitierisico's en fysieke risico's. Zulke systemen ondersteunen betere investeringsbeslissingen, naleving en veerkrachtplanning. Voor EcoVadis voedt een gedocumenteerde beoordeling van externe klimaatrisico's ook specifieke Milieuvragen (zie de fiches ENV7003/ENV7012)."""},
 "content_kind": "methodology",
 "themes": ["environment"],
 "topics": ["environnement", "carbone-ghg"],
 "keywords": {"en": ["climate risk", "physical risk", "transition risk", "monitoring system"],
              "fr": ["risque climatique", "risque physique", "risque de transition", "système de suivi"],
              "nl": ["klimaatrisico", "fysiek risico", "transitierisico", "monitoringsysteem"]},
 "source_note": SRC25,
 "related": ["ecovadis-and-ghg-baseline"],
},
{
 "id": "kb-0112",
 "slug": {"en": "are-lcas-required-for-cdp",
          "fr": "les-acv-sont-elles-obligatoires-pour-le-cdp",
          "nl": "zijn-lcas-verplicht-voor-cdp"},
 "title": {"en": "Must companies submit life cycle assessments (LCAs) for good governance scoring on CDP?",
           "fr": "Faut-il soumettre des analyses de cycle de vie (ACV) pour bien scorer en gouvernance au CDP ?",
           "nl": "Moet u levenscyclusanalyses (LCA's) indienen voor een goede governancescore bij CDP?"},
 "summary": {"en": "Full LCAs are not mandatory for all products, but conducting LCAs or similar analysis on main products is advised to support the CDP governance score; concentrating on core offerings balances resource use.",
             "fr": "Les ACV complètes ne sont pas obligatoires pour tous les produits, mais une ACV ou analyse similaire sur les produits principaux est conseillée pour soutenir le score de gouvernance CDP.",
             "nl": "Volledige LCA's zijn niet verplicht voor alle producten, maar een LCA of vergelijkbare analyse van de hoofdproducten is aangeraden om de CDP-governancescore te ondersteunen."},
 "body": {
  "en": """Full LCAs are **not mandatory for all products**, but conducting LCAs or similar analysis on your main products is advised to support the governance score. Concentrating on core offerings balances resource use and aligns with CDP expectations — a focused analysis of what you actually sell most beats a thin attempt to cover the whole portfolio.""",
  "fr": """Les ACV complètes ne sont **pas obligatoires pour tous les produits**, mais mener une ACV ou une analyse similaire sur vos produits principaux est conseillé pour soutenir le score de gouvernance. Se concentrer sur l'offre cœur équilibre l'usage des ressources et correspond aux attentes du CDP — une analyse ciblée de ce que vous vendez le plus vaut mieux qu'une tentative superficielle de couvrir tout le portefeuille.""",
  "nl": """Volledige LCA's zijn **niet verplicht voor alle producten**, maar een LCA of vergelijkbare analyse van uw hoofdproducten is aangeraden om de governancescore te ondersteunen. Focussen op het kernaanbod houdt het middelengebruik in evenwicht en strookt met de CDP-verwachtingen — een gerichte analyse van wat u het meest verkoopt is beter dan een dunne poging om het hele portfolio te dekken."""},
 "content_kind": "reporting",
 "themes": ["environment"],
 "topics": ["carbone-ghg", "methodologie"],
 "keywords": {"en": ["CDP", "life cycle assessment", "LCA", "governance score"],
              "fr": ["CDP", "analyse de cycle de vie", "ACV", "score de gouvernance"],
              "nl": ["CDP", "levenscyclusanalyse", "LCA", "governancescore"]},
 "source_note": SRC25,
 "related": ["ecovadis-and-ghg-baseline"],
},
{
 "id": "kb-0113",
 "slug": {"en": "handling-cdp-integrated-format",
          "fr": "gerer-le-format-integre-du-cdp",
          "nl": "omgaan-met-het-geintegreerde-cdp-formaat"},
 "title": {"en": "How can companies best handle the integrated format and new scoring system of CDP?",
           "fr": "Comment gérer au mieux le format intégré et le nouveau système de notation du CDP ?",
           "nl": "Hoe gaat u het best om met het geïntegreerde formaat en het nieuwe scoresysteem van CDP?"},
 "summary": {"en": "CDP encourages agile, flexible reporting on its integrated questionnaire and new platform: understand the scoring logic, use the available guidance, document sustainability narratives, and consider optional third-party verification for score and credibility.",
             "fr": "Le CDP encourage un reporting agile sur son questionnaire intégré et sa nouvelle plateforme : comprendre la logique de notation, documenter les narratifs, et envisager la vérification tierce optionnelle.",
             "nl": "CDP moedigt wendbare rapportering aan op zijn geïntegreerde vragenlijst en nieuwe platform: begrijp de scorelogica, documenteer de duurzaamheidsverhalen en overweeg optionele externe verificatie."},
 "body": {
  "en": """CDP now encourages **agile, flexible reporting** aligned with an integrated questionnaire and a new software platform. Companies should prepare by understanding the scoring logic, leveraging the available guidance, and documenting their sustainability narratives. Third-party verification, while optional, improves scores and credibility — and the same verified data strengthens your EcoVadis Reporting indicator.""",
  "fr": """Le CDP encourage désormais un **reporting agile et flexible**, aligné sur un questionnaire intégré et une nouvelle plateforme logicielle. Préparez-vous en comprenant la logique de notation, en exploitant les guides disponibles et en documentant vos narratifs de durabilité. La vérification tierce, bien qu'optionnelle, améliore les scores et la crédibilité — et les mêmes données vérifiées renforcent votre indicateur Reporting EcoVadis.""",
  "nl": """CDP moedigt nu **wendbare, flexibele rapportering** aan, afgestemd op een geïntegreerde vragenlijst en een nieuw softwareplatform. Bereid u voor door de scorelogica te begrijpen, de beschikbare gidsen te benutten en uw duurzaamheidsverhalen te documenteren. Externe verificatie is optioneel maar verbetert de scores en de geloofwaardigheid — en dezelfde geverifieerde data versterkt uw EcoVadis-indicator Rapportering."""},
 "content_kind": "reporting",
 "themes": ["environment"],
 "topics": ["carbone-ghg", "methodologie"],
 "keywords": {"en": ["CDP integrated questionnaire", "CDP scoring", "third-party verification"],
              "fr": ["questionnaire intégré CDP", "notation CDP", "vérification tierce"],
              "nl": ["geïntegreerde CDP-vragenlijst", "CDP-scoring", "externe verificatie"]},
 "source_note": SRC25,
 "related": ["ecovadis-and-ghg-baseline"],
},
]
