# FAQ objects kb-0114 – kb-0129 (source: EcoVadis FAQ 2026 (1) — getting started + evidence; kb-0122 merges validity/1-month rules from FAQ 2026 (2); kb-0128 merges both comment-field answers)
SRC1 = "EcoVadis FAQ 2026 (1) (Evernote, updated 2026-08-24)"
SRC2 = "EcoVadis FAQ 2026 (2) (Evernote, updated 2026-08-24)"

FAQS = [
{
 "id": "kb-0114",
 "slug": {"en": "preview-questionnaire-before-purchase",
          "fr": "previsualiser-le-questionnaire-avant-achat",
          "nl": "vragenlijst-bekijken-voor-aankoop"},
 "title": {"en": "Can you preview the EcoVadis questionnaire before purchasing an assessment?",
           "fr": "Peut-on prévisualiser le questionnaire EcoVadis avant d'acheter l'évaluation ?",
           "nl": "Kunt u de EcoVadis-vragenlijst bekijken vóór u een beoordeling koopt?"},
 "summary": {"en": "No full preview of the tailored questionnaire is available before initiating and paying. EcoVadis publishes an overview of the four themes and a Document Guide listing accepted evidence types; the exact scope depends on sector, size and geography.",
             "fr": "Aucune prévisualisation complète du questionnaire personnalisé n'est disponible avant de payer. EcoVadis publie un aperçu des quatre thèmes et un guide des documents acceptés ; le périmètre exact dépend du secteur, de la taille et de la géographie.",
             "nl": "Er is geen volledige preview van de gepersonaliseerde vragenlijst vóór betaling. EcoVadis publiceert een overzicht van de vier thema's en een documentengids; de exacte scope hangt af van sector, grootte en geografie."},
 "body": {
  "en": """A full preview of the tailored questionnaire is **not available before initiating and paying** for the assessment. EcoVadis provides an overview of the four sustainability themes on its website, and its Document Guide outlines the types of evidence accepted. Because the actual scope depends on your sector, size and geography, an experienced adviser can map the likely activated criteria for your profile before you commit — this is typically part of an ESGIM discovery call.""",
  "fr": """Une prévisualisation complète du questionnaire personnalisé n'est **pas disponible avant d'initier et de payer** l'évaluation. EcoVadis publie un aperçu des quatre thèmes de durabilité sur son site, et son guide des documents décrit les types de preuves acceptés. Le périmètre réel dépendant de votre secteur, taille et géographie, un conseiller expérimenté peut cartographier les critères probablement activés pour votre profil avant l'engagement — c'est typiquement l'objet d'un appel découverte ESGIM.""",
  "nl": """Een volledige preview van de gepersonaliseerde vragenlijst is **niet beschikbaar vóór u de beoordeling opstart en betaalt**. EcoVadis publiceert een overzicht van de vier duurzaamheidsthema's op zijn website, en de documentengids beschrijft de aanvaarde bewijstypes. Omdat de reële scope afhangt van uw sector, grootte en geografie, kan een ervaren adviseur de waarschijnlijk geactiveerde criteria voor uw profiel in kaart brengen vóór u zich engageert — typisch het onderwerp van een ESGIM-kennismakingsgesprek."""},
 "situations": ["S3"],
 "topics": ["questionnaire", "plateforme", "timing"],
 "keywords": {"en": ["preview questionnaire", "before purchase", "activated criteria", "Document Guide"],
              "fr": ["prévisualiser questionnaire", "avant achat", "critères activés", "guide des documents"],
              "nl": ["vragenlijst preview", "vóór aankoop", "geactiveerde criteria", "documentengids"]},
 "source_note": SRC1,
 "related": ["ecovadis-essentials-guide", "ecovadis-activated-criteria-by-sector"],
},
{
 "id": "kb-0115",
 "slug": {"en": "assessment-entity-level-group-or-subsidiary",
          "fr": "niveau-d-evaluation-groupe-ou-filiale",
          "nl": "beoordelingsniveau-groep-of-dochter"},
 "title": {"en": "At what entity level should the assessment be performed: subsidiary, holding or full group?",
           "fr": "À quel niveau faut-il faire l'évaluation : filiale, holding ou groupe entier ?",
           "nl": "Op welk niveau voert u de beoordeling uit: dochteronderneming, holding of volledige groep?"},
 "summary": {"en": "The right level depends on who requests the rating and where sustainability management is actually governed: an entity-level assessment covers one legal entity and is simpler; a group-level assessment covers all consolidated entities and activates the Coverage indicator.",
             "fr": "Le bon niveau dépend de qui demande la notation et d'où la durabilité est réellement gouvernée : l'évaluation d'entité couvre une entité légale et est plus simple ; l'évaluation groupe couvre toutes les entités consolidées et active l'indicateur Coverage.",
             "nl": "Het juiste niveau hangt af van wie de score vraagt en waar het duurzaamheidsbeheer werkelijk wordt aangestuurd: een entiteitsbeoordeling dekt één juridische entiteit en is eenvoudiger; een groepsbeoordeling dekt alle geconsolideerde entiteiten en activeert de Coverage-indicator."},
 "body": {
  "en": """The right level depends on **who your customer is requesting the rating from, and where your sustainability management is actually governed**. An entity-level assessment covers one legal entity and is simpler to manage. A group-level assessment covers all consolidated entities and activates the **Coverage indicator**, which measures the extent to which sustainability practices are deployed across the group — a real factor for large organisations, simplified for a single-site SME.""",
  "fr": """Le bon niveau dépend de **qui demande la notation chez votre client, et d'où votre gestion de la durabilité est réellement gouvernée**. Une évaluation au niveau de l'entité couvre une seule entité légale et est plus simple à gérer. Une évaluation au niveau du groupe couvre toutes les entités consolidées et active l'indicateur **Coverage**, qui mesure le déploiement des pratiques de durabilité à travers le groupe — un vrai facteur pour les grandes organisations, simplifié pour une PME monosite.""",
  "nl": """Het juiste niveau hangt af van **bij wie uw klant de score opvraagt, en waar uw duurzaamheidsbeheer werkelijk wordt aangestuurd**. Een beoordeling op entiteitsniveau dekt één juridische entiteit en is eenvoudiger te beheren. Een groepsbeoordeling dekt alle geconsolideerde entiteiten en activeert de **Coverage-indicator**, die meet hoe breed de duurzaamheidspraktijken over de groep zijn uitgerold — een echte factor voor grote organisaties, vereenvoudigd voor een kmo met één site."""},
 "situations": ["S3"],
 "topics": ["questionnaire", "methodologie"],
 "keywords": {"en": ["entity level", "group assessment", "Coverage indicator", "legal entity"],
              "fr": ["niveau d'entité", "évaluation groupe", "indicateur Coverage", "entité légale"],
              "nl": ["entiteitsniveau", "groepsbeoordeling", "Coverage-indicator", "juridische entiteit"]},
 "source_note": SRC1,
 "related": ["ecovadis-essentials-guide"],
},
{
 "id": "kb-0116",
 "slug": {"en": "submission-deadline-after-purchase",
          "fr": "delai-de-soumission-apres-achat",
          "nl": "indieningstermijn-na-aankoop"},
 "title": {"en": "Once the assessment is purchased, is there a deadline to submit the questionnaire?",
           "fr": "Une fois l'évaluation achetée, y a-t-il un délai pour soumettre le questionnaire ?",
           "nl": "Is er na de aankoop van de beoordeling een termijn om de vragenlijst in te dienen?"},
 "summary": {"en": "Yes: an initial deadline of about 6 weeks from questionnaire creation, self-extendable by up to 60 business days in total; after expiry a repurchase may be needed, though EcoVadis can reopen within 6 months of creation. Start evidence-gathering early.",
             "fr": "Oui : un délai initial d'environ 6 semaines, extensible soi-même jusqu'à 60 jours ouvrables au total ; après expiration, un rachat peut être nécessaire, mais EcoVadis peut rouvrir dans les 6 mois. Commencez tôt la collecte des preuves.",
             "nl": "Ja: een initiële termijn van ongeveer 6 weken, zelf verlengbaar tot 60 werkdagen in totaal; na het verstrijken kan een nieuwe aankoop nodig zijn, al kan EcoVadis binnen 6 maanden heropenen. Begin vroeg met bewijsverzameling."},
 "body": {
  "en": """Yes. Once an EcoVadis assessment is purchased, companies typically receive an initial submission deadline of about **6 weeks** from the date the questionnaire is created. If more time is needed, you can extend this deadline yourself by up to **60 business days in total**. If the questionnaire is not submitted within this window, the assessment period may expire and require repurchase — though you can contact EcoVadis to request a **reopening within 6 months** of the original creation date. Check your specific contract terms. Starting the evidence-gathering early is always preferable to compressing everything into the final weeks.""",
  "fr": """Oui. Après l'achat, l'entreprise reçoit généralement un délai initial de soumission d'environ **6 semaines** à partir de la création du questionnaire. Si besoin, vous pouvez l'étendre vous-même jusqu'à **60 jours ouvrables au total**. Si le questionnaire n'est pas soumis dans cette fenêtre, la période d'évaluation peut expirer et exiger un rachat — mais vous pouvez demander à EcoVadis une **réouverture dans les 6 mois** de la date de création. Vérifiez les termes de votre contrat. Commencer tôt la collecte des preuves vaut toujours mieux que tout compresser dans les dernières semaines.""",
  "nl": """Ja. Na de aankoop krijgt de onderneming doorgaans een initiële indieningstermijn van ongeveer **6 weken** vanaf de aanmaak van de vragenlijst. Indien nodig kunt u die zelf verlengen tot **60 werkdagen in totaal**. Wordt de vragenlijst niet binnen dat venster ingediend, dan kan de beoordelingsperiode vervallen en een nieuwe aankoop vereisen — al kunt u EcoVadis om een **heropening binnen 6 maanden** na de aanmaakdatum vragen. Controleer uw contractvoorwaarden. Vroeg beginnen met bewijsverzameling is altijd beter dan alles in de laatste weken te persen."""},
 "topics": ["timing", "plateforme"],
 "keywords": {"en": ["submission deadline", "6 weeks", "60 business days", "reopening"],
              "fr": ["délai de soumission", "6 semaines", "60 jours ouvrables", "réouverture"],
              "nl": ["indieningstermijn", "6 weken", "60 werkdagen", "heropening"]},
 "source_note": SRC1,
 "related": ["ecovadis-essentials-guide", "practical-ecovadis-tips"],
},
{
 "id": "kb-0117",
 "slug": {"en": "non-activated-criteria-in-questionnaire",
          "fr": "criteres-non-actives-dans-le-questionnaire",
          "nl": "niet-geactiveerde-criteria-in-de-vragenlijst"},
 "title": {"en": "Why do non-activated criteria still appear in the questionnaire, and why are answers to them rejected?",
           "fr": "Pourquoi des critères non activés apparaissent-ils dans le questionnaire, et pourquoi leurs réponses sont-elles rejetées ?",
           "nl": "Waarom verschijnen niet-geactiveerde criteria in de vragenlijst, en waarom worden antwoorden erop verworpen?"},
 "summary": {"en": "EcoVadis uses a universal questionnaire template and activates criteria per company profile; questions on non-activated criteria may stay visible, but evidence uploaded against them is assessed as irrelevant and does not contribute to the score.",
             "fr": "EcoVadis utilise un modèle universel et active les critères selon le profil ; les questions des critères non activés peuvent rester visibles, mais les preuves chargées dessus sont jugées non pertinentes et ne comptent pas.",
             "nl": "EcoVadis gebruikt een universeel sjabloon en activeert criteria per profiel; vragen van niet-geactiveerde criteria kunnen zichtbaar blijven, maar bewijs daartegen wordt als irrelevant beoordeeld en telt niet mee."},
 "body": {
  "en": """This is a platform design feature. EcoVadis uses a **universal questionnaire template** and activates or deactivates specific criteria based on your company profile — sector, size and geography. Questions relating to non-activated criteria may still be visible in the interface, but evidence uploaded against them will be **assessed as irrelevant and will not contribute to your score**. Focus your effort on the criteria that are active for your profile; your scorecard and corrective action plan identify which those are.""",
  "fr": """C'est une caractéristique de conception de la plateforme. EcoVadis utilise un **modèle de questionnaire universel** et active ou désactive des critères selon votre profil — secteur, taille, géographie. Les questions des critères non activés peuvent rester visibles dans l'interface, mais les preuves chargées dessus seront **jugées non pertinentes et ne contribueront pas à votre score**. Concentrez l'effort sur les critères actifs pour votre profil ; votre fiche d'évaluation et votre plan d'action correctif les identifient.""",
  "nl": """Dit is een ontwerpkeuze van het platform. EcoVadis gebruikt een **universeel vragenlijstsjabloon** en activeert of deactiveert criteria op basis van uw profiel — sector, grootte, geografie. Vragen van niet-geactiveerde criteria kunnen zichtbaar blijven in de interface, maar bewijs dat u ertegen oplaadt, wordt **als irrelevant beoordeeld en draagt niet bij aan uw score**. Richt de inspanning op de criteria die actief zijn voor uw profiel; uw scorecard en corrigerend actieplan identificeren welke dat zijn."""},
 "topics": ["questionnaire", "methodologie"],
 "keywords": {"en": ["non-activated criteria", "irrelevant evidence", "universal template", "activated criteria"],
              "fr": ["critères non activés", "preuve non pertinente", "modèle universel", "critères activés"],
              "nl": ["niet-geactiveerde criteria", "irrelevant bewijs", "universeel sjabloon", "geactiveerde criteria"]},
 "source_note": SRC1,
 "related": ["ecovadis-activated-criteria-by-sector"],
},
{
 "id": "kb-0118",
 "slug": {"en": "is-a-poor-score-publicly-visible",
          "fr": "un-mauvais-score-est-il-visible-publiquement",
          "nl": "is-een-slechte-score-publiek-zichtbaar"},
 "title": {"en": "If our score is poor, is it publicly shared or visible to others?",
           "fr": "Si notre score est mauvais, est-il partagé publiquement ou visible par d'autres ?",
           "nl": "Als onze score slecht is, wordt hij dan publiek gedeeld of zichtbaar voor anderen?"},
 "summary": {"en": "No: scorecards are not publicly shared by default and are visible only to buyers you actively share them with. Buyers who initiated or co-funded the assessment may see that it was completed, but no third party can access the score without your consent.",
             "fr": "Non : les fiches d'évaluation ne sont pas publiques par défaut et ne sont visibles que des acheteurs avec qui vous les partagez. Aucun tiers ne peut accéder au score sans votre consentement.",
             "nl": "Nee: scorecards zijn standaard niet publiek en alleen zichtbaar voor kopers met wie u ze actief deelt. Geen enkele derde krijgt toegang tot de score zonder uw toestemming."},
 "body": {
  "en": """No. EcoVadis scorecards are **not publicly shared by default**. Your score is only visible to buyers you actively choose to share it with, and a company that receives a poor score can decline to share it. Some buyers who initiated or co-funded the assessment may be able to see that it was completed without a scorecard being shared — which can itself be a signal — but **no third party can access your score without your consent**. Sharing settings are entirely within your control on the platform.""",
  "fr": """Non. Les fiches d'évaluation (scorecards) EcoVadis ne sont **pas partagées publiquement par défaut**. Votre score n'est visible que des acheteurs avec qui vous choisissez activement de le partager, et une entreprise mal notée peut refuser de le partager. Certains acheteurs qui ont initié ou cofinancé l'évaluation peuvent voir qu'elle a été complétée sans qu'une fiche soit partagée — ce qui peut être un signal en soi — mais **aucun tiers ne peut accéder à votre score sans votre consentement**. Les paramètres de partage sont entièrement sous votre contrôle.""",
  "nl": """Nee. EcoVadis-scorecards worden **standaard niet publiek gedeeld**. Uw score is alleen zichtbaar voor kopers met wie u hem actief deelt, en een onderneming met een slechte score kan weigeren hem te delen. Sommige kopers die de beoordeling initieerden of meefinancierden, kunnen zien dat ze werd afgerond zonder dat een scorecard werd gedeeld — wat op zich een signaal kan zijn — maar **geen enkele derde krijgt toegang tot uw score zonder uw toestemming**. De deelinstellingen staan volledig onder uw controle."""},
 "topics": ["plateforme", "donneur-d-ordres"],
 "keywords": {"en": ["score visibility", "scorecard sharing", "confidentiality", "poor score"],
              "fr": ["visibilité du score", "partage scorecard", "confidentialité", "mauvais score"],
              "nl": ["scorezichtbaarheid", "scorecard delen", "vertrouwelijkheid", "slechte score"]},
 "source_note": SRC1,
 "related": ["read-share-maximise-your-ecovadis-scorecard"],
},
{
 "id": "kb-0119",
 "slug": {"en": "how-does-a-reassessment-work",
          "fr": "comment-se-deroule-une-reevaluation",
          "nl": "hoe-verloopt-een-herbeoordeling"},
 "title": {"en": "How do we proceed with a reassessment?",
           "fr": "Comment procéder pour une réévaluation ?",
           "nl": "Hoe pakt u een herbeoordeling aan?"},
 "summary": {"en": "Same sequence as the first cycle, but easier: some answers are pre-filled, and previously submitted documents remain in the Document Library without counting against the new 55-document quota. Review pre-filled answers, update expired policies and KPIs, and run a gap analysis before submitting.",
             "fr": "Même séquence qu'au premier cycle, mais plus facile : réponses pré-remplies, documents précédents disponibles hors quota. Revoir le pré-rempli, actualiser politiques et KPI expirés, et faire une gap analysis avant de soumettre.",
             "nl": "Dezelfde volgorde als de eerste cyclus, maar makkelijker: sommige antwoorden zijn vooraf ingevuld en eerdere documenten blijven buiten het quotum beschikbaar. Herbekijk het vooraf ingevulde, actualiseer vervallen beleid en KPI's, en doe een gap-analyse vóór indiening."},
 "body": {
  "en": """When your scorecard approaches expiry, EcoVadis notifies you to initiate a new cycle. The process follows the same sequence: complete the questionnaire, upload updated evidence, submit. Importantly, **reassessments can be easier than first assessments**: some answers are pre-filled from your previous responses, and all previously submitted documents remain accessible in the Document Library **without counting against your new 55-document quota**.

The practical focus: review the pre-filled answers, update any expired or outdated policies and KPIs, add fresh evidence, and address open corrective action plan items. A structured gap analysis before submission is strongly recommended over simply relying on what was pre-filled.""",
  "fr": """Quand votre fiche d'évaluation approche de l'expiration, EcoVadis vous notifie pour initier un nouveau cycle. Le processus suit la même séquence : compléter le questionnaire, charger les preuves à jour, soumettre. Important : **une réévaluation peut être plus facile qu'une première évaluation** — certaines réponses sont pré-remplies à partir du cycle précédent, et tous les documents déjà soumis restent accessibles dans la bibliothèque **sans compter dans le nouveau quota de 55 documents**.

Le focus pratique : revoir les réponses pré-remplies, actualiser les politiques et KPI expirés ou obsolètes, ajouter des preuves fraîches, et traiter les points ouverts du plan d'action correctif. Une gap analysis structurée avant soumission est fortement recommandée plutôt que de se fier au pré-rempli.""",
  "nl": """Wanneer uw scorecard de vervaldatum nadert, verwittigt EcoVadis u om een nieuwe cyclus te starten. Het proces volgt dezelfde volgorde: vragenlijst invullen, geactualiseerd bewijs opladen, indienen. Belangrijk: **een herbeoordeling kan makkelijker zijn dan een eerste beoordeling** — sommige antwoorden zijn vooraf ingevuld op basis van de vorige cyclus, en alle eerder ingediende documenten blijven toegankelijk in de documentbibliotheek **zonder mee te tellen in het nieuwe quotum van 55 documenten**.

De praktische focus: herbekijk de vooraf ingevulde antwoorden, actualiseer vervallen of verouderd beleid en KPI's, voeg vers bewijs toe en werk de open punten van het corrigerend actieplan weg. Een gestructureerde gap-analyse vóór indiening is sterk aanbevolen in plaats van louter op het vooraf ingevulde te vertrouwen."""},
 "situations": ["S1", "S2"],
 "topics": ["questionnaire", "timing"],
 "keywords": {"en": ["reassessment", "pre-filled answers", "Document Library", "gap analysis"],
              "fr": ["réévaluation", "réponses pré-remplies", "bibliothèque de documents", "gap analysis"],
              "nl": ["herbeoordeling", "vooraf ingevulde antwoorden", "documentbibliotheek", "gap-analyse"]},
 "source_note": SRC1,
 "related": ["build-strong-ecovadis-submissions-consistently", "improve-your-ecovadis-score-fast"],
},
{
 "id": "kb-0120",
 "slug": {"en": "assessment-changes-to-prepare-for-2026",
          "fr": "changements-d-evaluation-a-anticiper-2026",
          "nl": "beoordelingswijzigingen-om-voor-te-bereiden-2026"},
 "title": {"en": "What changes to assessment expectations should companies prepare for in 2026?",
           "fr": "Quels changements d'exigences faut-il anticiper pour 2026 ?",
           "nl": "Op welke gewijzigde verwachtingen moet u zich voorbereiden in 2026?"},
 "summary": {"en": "Three developments: the materiality customisation pilot (sector-limited opt-out of non-material environmental topics), tightened reporting requirements (public standard-aligned report needed for Reporting scores above 50/100), and continuously rising medal thresholds (Silver moved from ~68 to ~73 points between July 2025 and May 2026).",
             "fr": "Trois évolutions : le pilote de personnalisation de la matérialité, des exigences de reporting durcies (rapport public aligné exigé au-delà de 50/100), et des seuils de médailles en hausse continue (Argent de ~68 à ~73 points entre juillet 2025 et mai 2026).",
             "nl": "Drie evoluties: het materialiteitspilootproject, strengere rapporteringseisen (publiek rapport vereist boven 50/100) en voortdurend stijgende medailledrempels (Zilver van ~68 naar ~73 punten tussen juli 2025 en mei 2026)."},
 "body": {
  "en": """Three developments are worth monitoring. First, the **materiality customisation pilot**, currently available to specific sectors, allows companies to opt out of non-material environmental topics, which changes the assessment scope. Second, **reporting requirements have tightened**: a public sustainability report aligned with a recognised standard is increasingly required to achieve Reporting scores above 50/100. Third, **medal thresholds continue rising** as the rated-company database grows: based on ESGIM's internal benchmarking, the approximate Silver score increased from 68 to 73 points between July 2025 and May 2026. Companies maintaining their score without improving will find their medal tier under pressure at reassessment.""",
  "fr": """Trois évolutions méritent d'être suivies. D'abord, le **pilote de personnalisation de la matérialité**, disponible pour certains secteurs, permet d'exclure les sujets environnementaux non matériels — ce qui change le périmètre d'évaluation. Ensuite, **les exigences de reporting se sont durcies** : un rapport de durabilité public aligné sur un standard reconnu est de plus en plus requis pour dépasser 50/100 en Reporting. Enfin, **les seuils de médailles continuent de monter** avec la croissance de la base : selon le benchmark interne d'ESGIM, le score approximatif de l'Argent est passé de 68 à 73 points entre juillet 2025 et mai 2026. Une entreprise qui maintient son score sans progresser verra sa médaille sous pression à la réévaluation.""",
  "nl": """Drie evoluties verdienen opvolging. Ten eerste laat het **materialiteitspilootproject**, beschikbaar voor bepaalde sectoren, toe om niet-materiële milieuonderwerpen uit te sluiten — wat de beoordelingsscope wijzigt. Ten tweede zijn de **rapporteringseisen verstrengd**: een publiek duurzaamheidsrapport, afgestemd op een erkende standaard, is steeds vaker vereist om boven 50/100 te scoren op Rapportering. Ten derde **blijven de medailledrempels stijgen** met de groei van de databank: volgens de interne benchmark van ESGIM steeg de indicatieve Zilverscore van 68 naar 73 punten tussen juli 2025 en mei 2026. Wie zijn score behoudt zonder te verbeteren, ziet zijn medaille onder druk komen bij de herbeoordeling."""},
 "topics": ["rising-bar", "methodologie", "vsme-csrd"],
 "keywords": {"en": ["2026 changes", "materiality pilot", "reporting 50 cap", "rising thresholds"],
              "fr": ["changements 2026", "pilote matérialité", "plafond reporting 50", "seuils en hausse"],
              "nl": ["wijzigingen 2026", "materialiteitspiloot", "rapporteringsplafond 50", "stijgende drempels"]},
 "source_note": SRC1,
 "related": ["whats-changing-in-2026", "ecovadis-rising-standards-2026", "ecovadis-methodology-updates-q2-2026"],
},
{
 "id": "kb-0121",
 "slug": {"en": "levers-for-companies-outside-csrd",
          "fr": "leviers-pour-entreprises-hors-csrd",
          "nl": "hefbomen-voor-ondernemingen-buiten-csrd"},
 "title": {"en": "We are not subject to CSRD — what levers ensure our sustainability work is recognised by EcoVadis?",
           "fr": "Nous ne sommes pas soumis à la CSRD — quels leviers pour faire reconnaître notre travail de durabilité par EcoVadis ?",
           "nl": "Wij vallen niet onder de CSRD — welke hefbomen zorgen dat EcoVadis ons duurzaamheidswerk erkent?"},
 "summary": {"en": "CSRD compliance is not a prerequisite: VSME (EFRAG) is formally recognised (Basic up to 75/100 on Reporting, full VSME up to 100/100), GRI remains highly effective, and endorsements like UN Global Compact and SBTi add score independently of regulatory status. Without any public report, Reporting caps at 50/100.",
             "fr": "La conformité CSRD n'est pas un prérequis : la VSME est reconnue (Basic jusqu'à 75/100, complète jusqu'à 100/100), la GRI reste efficace, et les adhésions (UNGC, SBTi) ajoutent du score. Sans rapport public, le Reporting plafonne à 50/100.",
             "nl": "CSRD-naleving is geen voorwaarde: VSME is erkend (Basic tot 75/100, volledig tot 100/100), GRI blijft doeltreffend, en aansluitingen (UNGC, SBTi) voegen score toe. Zonder publiek rapport plafonneert Rapportering op 50/100."},
 "body": {
  "en": """CSRD compliance is **not a prerequisite** for a strong EcoVadis score. Companies outside CSRD scope have several effective routes. The **VSME** (Voluntary SME Standard, developed by EFRAG) is now formally recognised by EcoVadis as a reporting framework: the Basic Module achieves up to **75/100** in the Reporting indicator, and the full VSME (Basic and Comprehensive) can reach **100/100**. **GRI** reporting remains highly effective and accessible. Without any public report, the maximum achievable Reporting score is **50/100**. Endorsements such as **UN Global Compact** and **Science-Based Targets** commitments add score independently of regulatory status.""",
  "fr": """La conformité CSRD n'est **pas un prérequis** pour un bon score EcoVadis. Hors du périmètre CSRD, plusieurs voies efficaces existent. La **VSME** (standard volontaire PME développé par l'EFRAG) est désormais formellement reconnue par EcoVadis comme cadre de reporting : le module Basic atteint jusqu'à **75/100** en Reporting, et la VSME complète (Basic et Comprehensive) peut atteindre **100/100**. Le reporting **GRI** reste très efficace et accessible. Sans aucun rapport public, le score Reporting maximal est de **50/100**. Les adhésions comme le **Pacte mondial des Nations unies (UNGC)** et les engagements **Science-Based Targets** ajoutent du score indépendamment du statut réglementaire.""",
  "nl": """CSRD-naleving is **geen voorwaarde** voor een sterke EcoVadis-score. Buiten de CSRD-scope bestaan meerdere doeltreffende routes. De **VSME** (vrijwillige kmo-standaard van EFRAG) is nu formeel erkend door EcoVadis als rapporteringskader: de Basic-module haalt tot **75/100** op de indicator Rapportering, en de volledige VSME (Basic en Comprehensive) kan **100/100** bereiken. **GRI**-rapportering blijft zeer doeltreffend en toegankelijk. Zonder enig publiek rapport is de maximale Rapporteringsscore **50/100**. Aansluitingen zoals het **UN Global Compact** en **Science-Based Targets**-engagementen voegen score toe, los van de regelgevende status."""},
 "content_kind": "reporting",
 "topics": ["vsme-csrd", "methodologie"],
 "keywords": {"en": ["CSRD not required", "VSME 75", "GRI", "UN Global Compact", "SBTi", "Reporting cap 50"],
              "fr": ["CSRD non requise", "VSME 75", "GRI", "Pacte mondial", "SBTi", "plafond Reporting 50"],
              "nl": ["CSRD niet vereist", "VSME 75", "GRI", "UN Global Compact", "SBTi", "Rapporteringsplafond 50"]},
 "source_note": SRC1,
 "related": ["whats-changing-in-2026", "ecovadis-rising-standards-2026"],
},
{
 "id": "kb-0122",
 "slug": {"en": "document-quality-validity-and-strong-policies",
          "fr": "qualite-validite-des-documents-et-politiques-solides",
          "nl": "documentkwaliteit-geldigheid-en-sterk-beleid"},
 "title": {"en": "What are the quality and validity requirements for documents, and what makes a strong policy?",
           "fr": "Quelles sont les exigences de qualité et de validité des documents, et qu'est-ce qu'une politique solide ?",
           "nl": "Wat zijn de kwaliteits- en geldigheidseisen voor documenten, en wat maakt een beleid sterk?"},
 "summary": {"en": "Documents are assessed on relevance, completeness and recency; they must carry the company name or logo and a date, be issued more than one month before submission, and reflect pre-existing operational systems. Validity: 8 years for policies and actions, 2 years for KPI/reporting, certifications until expiry. A strong policy has scope, governance ownership, a review mechanism and qualitative plus quantitative commitments.",
             "fr": "Les documents sont évalués sur pertinence, complétude et récence ; ils doivent porter nom/logo et date, être émis plus d'un mois avant la soumission, et refléter des systèmes préexistants. Validité : 8 ans (politiques, actions), 2 ans (KPI/reporting), certifications jusqu'à échéance. Une politique solide a un périmètre, une gouvernance, un mécanisme de revue et des engagements qualitatifs et quantitatifs.",
             "nl": "Documenten worden beoordeeld op relevantie, volledigheid en recentheid; ze moeten naam/logo en datum dragen, meer dan één maand vóór indiening zijn uitgegeven en bestaande systemen weerspiegelen. Geldigheid: 8 jaar (beleid, acties), 2 jaar (KPI/rapportering), certificaten tot vervaldatum. Een sterk beleid heeft een scope, governance, een reviewmechanisme en kwalitatieve plus kwantitatieve engagementen."},
 "body": {
  "en": """EcoVadis assesses documents on three dimensions: **relevance, completeness and recency**. Generic templates minimally adapted for EcoVadis are not accepted; documents must reflect **pre-existing, operational systems** and must be issued **more than one month before the questionnaire submission date** — a document created specifically for the assessment will not work. Every document must carry the **company name or logo** and a **date**; missing either can cause rejection regardless of content. You can check each document's age and remaining validity in the platform's Document Library.

Validity periods by type: **policies and actions documents — 8 years**; **KPI and reporting documents — 2 years**; **certifications — until their stated expiry date**.

A strong policy contains: a clear statement of intent aligned with the sustainability topic; qualitative and, where relevant, quantitative targets (SMART); the **scope** it applies to; **named governance ownership** (who owns and reviews it); a **review mechanism**; a date of approval; and the company identifier. Procedures add strength by showing how commitments are operationalised — who does what, when, and how it is monitored. Creating a new version of a structurally sound, regularly reviewed policy is not automatically beneficial: updating the review date is sufficient.""",
  "fr": """EcoVadis évalue les documents sur trois dimensions : **pertinence, complétude et récence**. Les modèles génériques à peine adaptés ne sont pas acceptés ; les documents doivent refléter des **systèmes opérationnels préexistants** et être émis **plus d'un mois avant la date de soumission** — un document créé spécifiquement pour l'évaluation ne fonctionne pas. Chaque document doit porter le **nom ou le logo de l'entreprise** et une **date** ; l'absence de l'un des deux peut entraîner le rejet, quel que soit le contenu. L'âge et la validité restante de chaque document se vérifient dans la bibliothèque de documents de la plateforme.

Validité par type : **politiques et actions — 8 ans** ; **KPI et reporting — 2 ans** ; **certifications — jusqu'à leur date d'échéance**.

Une politique solide contient : une déclaration d'intention claire alignée sur le sujet ; des objectifs qualitatifs et, si pertinent, quantitatifs (SMART) ; le **périmètre** d'application ; une **gouvernance nommée** (qui la possède et la revoit) ; un **mécanisme de revue** ; une date d'approbation ; et l'identifiant de l'entreprise. Les procédures renforcent en montrant l'opérationnalisation — qui fait quoi, quand, et comment c'est suivi. Créer une nouvelle version d'une politique structurellement saine et régulièrement revue n'apporte rien : actualiser la date de revue suffit.""",
  "nl": """EcoVadis beoordeelt documenten op drie dimensies: **relevantie, volledigheid en recentheid**. Generieke sjablonen die minimaal zijn aangepast, worden niet aanvaard; documenten moeten **bestaande, operationele systemen** weerspiegelen en **meer dan één maand vóór de indieningsdatum** zijn uitgegeven — een document dat speciaal voor de beoordeling is gemaakt, werkt niet. Elk document moet de **naam of het logo van de onderneming** en een **datum** dragen; ontbreekt een van beide, dan kan het worden verworpen ongeacht de inhoud. De leeftijd en resterende geldigheid van elk document controleert u in de documentbibliotheek van het platform.

Geldigheid per type: **beleids- en actiedocumenten — 8 jaar**; **KPI- en rapporteringsdocumenten — 2 jaar**; **certificaten — tot hun vervaldatum**.

Een sterk beleid bevat: een heldere intentieverklaring afgestemd op het onderwerp; kwalitatieve en, waar relevant, kwantitatieve doelen (SMART); de **scope**; een **benoemde governance** (wie het beheert en herziet); een **reviewmechanisme**; een goedkeuringsdatum; en de bedrijfsidentificatie. Procedures versterken door de operationalisering te tonen — wie doet wat, wanneer, en hoe wordt het opgevolgd. Een nieuwe versie maken van een structureel gezond, regelmatig herzien beleid brengt niets op: de reviewdatum actualiseren volstaat."""},
 "content_kind": "methodology",
 "topics": ["preuves", "questionnaire", "methodologie"],
 "keywords": {"en": ["document validity", "8 years", "2 years", "one month rule", "strong policy", "company logo"],
              "fr": ["validité documents", "8 ans", "2 ans", "règle un mois", "politique solide", "logo entreprise"],
              "nl": ["documentgeldigheid", "8 jaar", "2 jaar", "één-maandregel", "sterk beleid", "bedrijfslogo"]},
 "source_note": SRC1 + " + " + SRC2,
 "related": ["supporting-documents-for-xs-companies", "build-strong-ecovadis-submissions-consistently"],
},
{
 "id": "kb-0123",
 "slug": {"en": "parent-or-sister-company-documentation",
          "fr": "documents-de-maison-mere-ou-societe-soeur",
          "nl": "documenten-van-moeder-of-zusterbedrijf"},
 "title": {"en": "Is documentation issued in the name of a parent or sister company accepted?",
           "fr": "Les documents au nom d'une maison mère ou d'une société sœur sont-ils acceptés ?",
           "nl": "Worden documenten op naam van een moeder- of zusterbedrijf aanvaard?"},
 "summary": {"en": "Parent documentation can be accepted when it covers and is implemented by the assessed entity — policies, endorsements and measures yes; reporting only if disaggregated by entity; certifications only if the assessed company's scope is explicitly mentioned. Sister-company documentation is never accepted.",
             "fr": "Les documents de la maison mère sont acceptés s'ils couvrent l'entité évaluée — politiques, adhésions, mesures oui ; le reporting seulement s'il est désagrégé par entité ; les certifications seulement si le périmètre de l'entité y est mentionné. Les documents de sociétés sœurs ne sont jamais acceptés.",
             "nl": "Documenten van de moedermaatschappij worden aanvaard als ze de beoordeelde entiteit dekken — beleid, aansluitingen en maatregelen wel; rapportering alleen indien uitgesplitst per entiteit; certificaten alleen als de scope van de entiteit expliciet wordt vermeld. Documenten van zusterbedrijven worden nooit aanvaard."},
 "body": {
  "en": """Usability depends entirely on the assessed scope. **Parent company** documentation can be accepted, provided it covers and is implemented by the assessed entity: **policies and endorsements** set by the parent are accepted; **measures** implemented by the parent are accepted; **reporting** from the parent is accepted only if results are **disaggregated by entity** and clearly represent the assessed company's performance separately — consolidated group results that do not isolate the assessed company are not accepted; **certifications** issued for the parent are not valid unless the assessed company's scope is explicitly mentioned in the certificate.

**Sister company** documentation is not accepted: a sister company is a separate legal entity.""",
  "fr": """L'utilisabilité dépend entièrement du périmètre évalué. Les documents de la **maison mère** peuvent être acceptés, à condition de couvrir l'entité évaluée et d'y être appliqués : les **politiques et adhésions** fixées par la mère sont acceptées ; les **mesures** mises en œuvre par la mère sont acceptées ; le **reporting** de la mère n'est accepté que si les résultats sont **désagrégés par entité** et représentent clairement la performance de l'entité évaluée séparément — des résultats consolidés groupe qui n'isolent pas l'entité ne sont pas acceptés ; les **certifications** émises pour la mère ne sont valides que si le périmètre de l'entité évaluée est explicitement mentionné dans le certificat.

Les documents d'une **société sœur** ne sont pas acceptés : c'est une entité légale distincte.""",
  "nl": """De bruikbaarheid hangt volledig af van de beoordeelde scope. Documenten van de **moedermaatschappij** kunnen worden aanvaard, mits ze de beoordeelde entiteit dekken en er worden toegepast: **beleid en aansluitingen** van de moeder worden aanvaard; **maatregelen** door de moeder uitgevoerd worden aanvaard; **rapportering** van de moeder wordt alleen aanvaard als de resultaten **per entiteit zijn uitgesplitst** en de prestaties van de beoordeelde entiteit afzonderlijk weergeven — geconsolideerde groepsresultaten zonder uitsplitsing worden niet aanvaard; **certificaten** op naam van de moeder zijn alleen geldig als de scope van de beoordeelde entiteit expliciet in het certificaat staat.

Documenten van een **zusterbedrijf** worden niet aanvaard: dat is een aparte juridische entiteit."""},
 "content_kind": "methodology",
 "topics": ["preuves", "questionnaire"],
 "keywords": {"en": ["parent company documents", "sister company", "disaggregated reporting", "certification scope"],
              "fr": ["documents maison mère", "société sœur", "reporting désagrégé", "périmètre de certification"],
              "nl": ["documenten moedermaatschappij", "zusterbedrijf", "uitgesplitste rapportering", "certificaatscope"]},
 "source_note": SRC1,
 "related": ["build-strong-ecovadis-submissions-consistently"],
},
{
 "id": "kb-0124",
 "slug": {"en": "keep-or-delete-rejected-documents",
          "fr": "garder-ou-supprimer-les-documents-rejetes",
          "nl": "verworpen-documenten-bewaren-of-verwijderen"},
 "title": {"en": "Should automatically rejected documents be deleted or kept?",
           "fr": "Faut-il supprimer ou garder les documents rejetés automatiquement ?",
           "nl": "Moet u automatisch verworpen documenten verwijderen of bewaren?"},
 "summary": {"en": "Keep them: rejected documents do not count against the submission, the rejection reason is recorded in Score Details, and deleting them removes information useful at reassessment.",
             "fr": "Gardez-les : ils ne comptent pas contre la soumission, la raison du rejet est enregistrée dans les détails du score, et les supprimer efface une information utile à la réévaluation.",
             "nl": "Bewaar ze: ze tellen niet mee tegen de indiening, de verwerpingsreden staat in de scoredetails, en ze verwijderen wist informatie die nuttig is bij de herbeoordeling."},
 "body": {
  "en": """**Keep them.** Automatically rejected documents do not count against your submission, and the rejection reason is recorded in your Score Details section. Deleting them removes information that may be useful at reassessment — particularly for understanding why certain evidence was redundant or how to consolidate documentation for future cycles. Review the rejection reason in Score Details before deciding whether to revise or replace.""",
  "fr": """**Gardez-les.** Les documents rejetés automatiquement ne comptent pas contre votre soumission, et la raison du rejet est enregistrée dans la section des détails du score. Les supprimer efface une information potentiellement utile à la réévaluation — notamment pour comprendre pourquoi certaines preuves étaient redondantes ou comment consolider la documentation aux cycles suivants. Examinez la raison du rejet dans les détails du score avant de décider de réviser ou de remplacer.""",
  "nl": """**Bewaar ze.** Automatisch verworpen documenten tellen niet mee tegen uw indiening, en de verwerpingsreden wordt geregistreerd in de sectie scoredetails. Ze verwijderen wist informatie die nuttig kan zijn bij de herbeoordeling — vooral om te begrijpen waarom bepaald bewijs overbodig was of hoe u de documentatie voor toekomstige cycli kunt consolideren. Bekijk de verwerpingsreden in de scoredetails vóór u beslist te herzien of te vervangen."""},
 "topics": ["preuves", "plateforme"],
 "keywords": {"en": ["rejected documents", "Score Details", "rejection reason"],
              "fr": ["documents rejetés", "détails du score", "raison du rejet"],
              "nl": ["verworpen documenten", "scoredetails", "verwerpingsreden"]},
 "source_note": SRC1,
 "related": ["build-strong-ecovadis-submissions-consistently"],
},
{
 "id": "kb-0125",
 "slug": {"en": "kpi-document-accepted-then-rejected",
          "fr": "document-kpi-accepte-puis-rejete",
          "nl": "kpi-document-eerst-aanvaard-dan-verworpen"},
 "title": {"en": "Why was a KPI attachment accepted one year but rejected on resubmission?",
           "fr": "Pourquoi une pièce KPI acceptée une année est-elle rejetée à la resoumission ?",
           "nl": "Waarom werd een KPI-bijlage het ene jaar aanvaard en bij herindiening verworpen?"},
 "summary": {"en": "Usually document expiry: KPI and reporting documents are valid for a maximum of two years from the reporting period. Methodology updates can also raise requirements. The rejection reason in Score Details usually identifies the specific gap.",
             "fr": "Le plus souvent l'expiration : les documents KPI/reporting sont valides deux ans maximum à partir de la période de reporting. Les mises à jour méthodologiques peuvent aussi durcir les exigences. La raison du rejet dans les détails du score identifie généralement l'écart.",
             "nl": "Meestal de vervaldatum: KPI-/rapporteringsdocumenten zijn maximaal twee jaar geldig vanaf de rapporteringsperiode. Methodologie-updates kunnen de eisen ook verhogen. De verwerpingsreden in de scoredetails identificeert doorgaans de kloof."},
 "body": {
  "en": """The most common reason is **document expiry**: KPI and reporting documents are valid for a maximum of **two years from the reporting period**. A KPI document within the validity window at the previous cycle may have aged out by reassessment.

Another reason is a **methodology update**: EcoVadis periodically revises its requirements for data granularity, coverage thresholds or framework alignment for specific indicators. These changes are published in the Help Centre, typically ahead of the cycle they apply to, and can make a previously accepted document fall short of current standards. The rejection reason in Score Details usually identifies the specific gap; if unclear, a structured review against current document requirements — or a formal debrief with EcoVadis — clarifies what to update.""",
  "fr": """La raison la plus fréquente est **l'expiration** : les documents KPI et reporting sont valides **deux ans maximum à partir de la période de reporting**. Un document dans la fenêtre de validité au cycle précédent peut être périmé à la réévaluation.

Autre raison : une **mise à jour méthodologique**. EcoVadis révise périodiquement ses exigences de granularité des données, de seuils de couverture ou d'alignement sur les référentiels pour certains indicateurs. Ces changements sont publiés dans le centre d'aide, généralement avant le cycle concerné, et peuvent rendre insuffisant un document accepté auparavant. La raison du rejet dans les détails du score identifie généralement l'écart précis ; si elle reste floue, une revue structurée face aux exigences actuelles — ou un débrief formel avec EcoVadis — clarifie ce qu'il faut actualiser.""",
  "nl": """De meest voorkomende reden is **de vervaldatum**: KPI- en rapporteringsdocumenten zijn maximaal **twee jaar geldig vanaf de rapporteringsperiode**. Een document dat in de vorige cyclus binnen de geldigheidsperiode viel, kan bij de herbeoordeling verouderd zijn.

Een andere reden: een **methodologie-update**. EcoVadis herziet periodiek zijn eisen rond datagranulariteit, dekkingsdrempels of afstemming op referentiekaders voor bepaalde indicatoren. Die wijzigingen worden in het Help Centre gepubliceerd, doorgaans vóór de cyclus waarop ze van toepassing zijn, en kunnen een eerder aanvaard document ontoereikend maken. De verwerpingsreden in de scoredetails identificeert meestal de precieze kloof; blijft ze onduidelijk, dan verheldert een gestructureerde review tegen de huidige eisen — of een formele debrief met EcoVadis — wat u moet actualiseren."""},
 "situations": ["S1", "S2"],
 "content_kind": "methodology",
 "topics": ["preuves", "methodologie"],
 "keywords": {"en": ["KPI rejected", "document expiry", "two years", "methodology update"],
              "fr": ["KPI rejeté", "expiration document", "deux ans", "mise à jour méthodologique"],
              "nl": ["KPI verworpen", "documentvervaldatum", "twee jaar", "methodologie-update"]},
 "source_note": SRC1,
 "related": ["ecovadis-methodology-updates-q2-2026", "build-strong-ecovadis-submissions-consistently"],
},
{
 "id": "kb-0126",
 "slug": {"en": "evidence-of-implementation-vs-paper-policies",
          "fr": "preuves-de-mise-en-oeuvre-vs-politiques-papier",
          "nl": "bewijs-van-uitvoering-versus-papieren-beleid"},
 "title": {"en": "What type of evidence best demonstrates actual implementation, versus just having policies on paper?",
           "fr": "Quel type de preuve démontre le mieux la mise en œuvre réelle, au-delà des politiques sur papier ?",
           "nl": "Welk type bewijs toont werkelijke uitvoering het best aan, voorbij beleid op papier?"},
 "summary": {"en": "Strong scores require all three PAR layers. Implementation evidence: training records, internal audit reports, procedures, handbooks, codes of conduct — and third-party certifications (ISO 14001, SMETA) carry extra weight through external verification. Results evidence shows outcomes: KPIs over time, progress against targets.",
             "fr": "Un bon score exige les trois couches P-A-R. Preuves de mise en œuvre : registres de formation, rapports d'audit interne, procédures, manuels, codes de conduite — et les certifications tierces (ISO 14001, SMETA) pèsent plus par la vérification externe. Les preuves de Résultats montrent les effets : KPI dans le temps, progrès vers les objectifs.",
             "nl": "Een sterke score vereist de drie P-A-R-lagen. Uitvoeringsbewijs: opleidingsregisters, interne auditrapporten, procedures, handboeken, gedragscodes — en externe certificaten (ISO 14001, SMETA) wegen zwaarder door de externe verificatie. Resultaatbewijs toont uitkomsten: KPI's in de tijd, vooruitgang naar doelen."},
 "body": {
  "en": """EcoVadis applies the **PAR framework (Policies, Actions, Results)** and strong scores require all three layers. A policy alone demonstrates intent; to show it is being put into practice, the evidence needs to reflect activity actually happening in the organisation.

The most convincing implementation evidence includes: **training records, internal audit or inspection reports, process and procedure documents, employee handbooks, and codes of conduct**. For higher scores, independent third-party certifications (such as **ISO 14001 or SMETA audits**) carry significant weight because they involve external verification rather than self-reporting. Results evidence goes one step further by showing outcomes: **KPIs tracked over time, progress against targets, and measurable performance data**.""",
  "fr": """EcoVadis applique le **modèle P-A-R (Politiques, Actions, Résultats)** et un bon score exige les trois couches. Une politique seule démontre l'intention ; pour montrer qu'elle est appliquée, la preuve doit refléter une activité réelle dans l'organisation.

Les preuves de mise en œuvre les plus convaincantes : **registres de formation, rapports d'audit ou d'inspection internes, documents de processus et de procédure, manuels employés, codes de conduite**. Pour les scores supérieurs, les certifications tierces indépendantes (comme **ISO 14001 ou un audit SMETA**) pèsent lourd parce qu'elles impliquent une vérification externe plutôt qu'une auto-déclaration. Les preuves de Résultats vont un cran plus loin en montrant les effets : **KPI suivis dans le temps, progrès vers les objectifs, données de performance mesurables**.""",
  "nl": """EcoVadis past het **P-A-R-model (Beleid, Acties, Resultaten)** toe en een sterke score vereist de drie lagen. Een beleid alleen toont intentie; om te tonen dat het wordt toegepast, moet het bewijs een activiteit weerspiegelen die werkelijk in de organisatie plaatsvindt.

Het meest overtuigende uitvoeringsbewijs: **opleidingsregisters, interne audit- of inspectierapporten, proces- en proceduredocumenten, personeelshandboeken, gedragscodes**. Voor hogere scores wegen onafhankelijke externe certificaten (zoals **ISO 14001 of een SMETA-audit**) zwaar door, omdat ze externe verificatie inhouden in plaats van zelfrapportering. Resultaatbewijs gaat een stap verder door uitkomsten te tonen: **KPI's opgevolgd in de tijd, vooruitgang tegenover doelen, meetbare prestatiedata**."""},
 "content_kind": "methodology",
 "topics": ["preuves", "methodologie"],
 "keywords": {"en": ["implementation evidence", "PAR framework", "training records", "ISO 14001", "SMETA"],
              "fr": ["preuves de mise en œuvre", "modèle P-A-R", "registres de formation", "ISO 14001", "SMETA"],
              "nl": ["uitvoeringsbewijs", "P-A-R-model", "opleidingsregisters", "ISO 14001", "SMETA"]},
 "source_note": SRC1,
 "related": ["understanding-the-ecovadis-scorecard", "build-strong-ecovadis-submissions-consistently"],
},
{
 "id": "kb-0127",
 "slug": {"en": "most-common-documentation-gaps-smes",
          "fr": "lacunes-documentaires-les-plus-frequentes-pme",
          "nl": "meest-voorkomende-documentatiekloven-kmo"},
 "title": {"en": "For first-time assessments and SMEs: what are the most common documentation gaps?",
           "fr": "Pour les premières évaluations et les PME : quelles sont les lacunes documentaires les plus fréquentes ?",
           "nl": "Voor eerste beoordelingen en kmo's: wat zijn de meest voorkomende documentatiekloven?"},
 "summary": {"en": "Four gaps recur: no public sustainability report or multi-year KPI summary (caps Reporting at 50/100); a Code of Conduct without acknowledgement evidence; a procurement policy without supplier sustainability requirements; environmental policies citing targets without baseline data or tracking.",
             "fr": "Quatre lacunes reviennent : pas de rapport public ni de synthèse KPI pluriannuelle (Reporting plafonné à 50/100) ; un code de conduite sans preuve de prise de connaissance ; une politique achats sans exigences durabilité fournisseurs ; des politiques environnementales sans données de référence ni suivi.",
             "nl": "Vier kloven keren terug: geen publiek rapport of meerjarige KPI-synthese (Rapportering geplafonneerd op 50/100); een gedragscode zonder ontvangstbewijs; een inkoopbeleid zonder duurzaamheidseisen voor leveranciers; milieubeleid met doelen zonder nulmeting of opvolging."},
 "body": {
  "en": """Four gaps appear consistently. First, **no public sustainability report or multi-year KPI summary**, which caps Reporting at 50/100. Second, a **Code of Conduct without evidence that employees have received and acknowledged it**. Third, a **procurement policy with no explicit sustainability requirements for suppliers**. Fourth, **environmental policies that reference targets without providing baseline data or a tracking mechanism**. All four are fixable within one cycle — and fixing them is largely a formalisation exercise, not a transformation programme.""",
  "fr": """Quatre lacunes reviennent systématiquement. Un : **pas de rapport de durabilité public ni de synthèse KPI pluriannuelle**, ce qui plafonne le Reporting à 50/100. Deux : un **code de conduite sans preuve que les employés l'ont reçu et pris en connaissance**. Trois : une **politique d'achats sans exigences de durabilité explicites pour les fournisseurs**. Quatre : des **politiques environnementales qui citent des objectifs sans données de référence ni mécanisme de suivi**. Les quatre se corrigent en un cycle — et c'est surtout un exercice de formalisation, pas un programme de transformation.""",
  "nl": """Vier kloven keren systematisch terug. Eén: **geen publiek duurzaamheidsrapport of meerjarige KPI-synthese**, wat Rapportering op 50/100 plafonneert. Twee: een **gedragscode zonder bewijs dat de medewerkers ze hebben ontvangen en bevestigd**. Drie: een **inkoopbeleid zonder expliciete duurzaamheidseisen voor leveranciers**. Vier: **milieubeleid dat doelen vermeldt zonder nulmetingsdata of opvolgingsmechanisme**. Alle vier zijn binnen één cyclus te verhelpen — en dat is vooral een formaliseringsoefening, geen transformatieprogramma."""},
 "situations": ["S3", "S1"],
 "topics": ["preuves", "questionnaire"],
 "keywords": {"en": ["documentation gaps", "reporting cap 50", "code of conduct acknowledgement", "baseline data"],
              "fr": ["lacunes documentaires", "plafond reporting 50", "prise de connaissance code de conduite", "données de référence"],
              "nl": ["documentatiekloven", "rapporteringsplafond 50", "bevestiging gedragscode", "nulmetingsdata"]},
 "source_note": SRC1,
 "related": ["supporting-documents-for-xs-companies", "from-committed-badge-to-bronze"],
},
{
 "id": "kb-0128",
 "slug": {"en": "free-text-comment-field-role",
          "fr": "role-du-champ-de-commentaire-libre",
          "nl": "rol-van-het-vrije-commentaarveld"},
 "title": {"en": "How important is the free-text comment field, and what should go in it?",
           "fr": "Quelle est l'importance du champ de commentaire libre, et qu'y mettre ?",
           "nl": "Hoe belangrijk is het vrije commentaarveld, en wat zet u erin?"},
 "summary": {"en": "Analysts read comments but never award points on comments alone: the field supplements documents, does not count against the 55-document limit, and is best used to point the analyst to the exact page or clause in an uploaded document. Keep comments brief and precise.",
             "fr": "Les analystes lisent les commentaires mais n'attribuent jamais de points sur cette seule base : le champ complète les documents, ne compte pas dans la limite de 55, et sert surtout à pointer la page ou la clause exacte d'un document chargé. Restez bref et précis.",
             "nl": "Analisten lezen de commentaren maar kennen er nooit punten op toe: het veld vult documenten aan, telt niet mee in de limiet van 55, en dient vooral om de analist naar de exacte pagina of clausule van een opgeladen document te wijzen. Houd het kort en precies."},
 "body": {
  "en": """EcoVadis analysts read the comment fields, but **points are never awarded on comments alone** — the field supplements documentation, it does not replace it. A well-written comment alongside a weak or missing document will not improve the score for that question. The field sits **outside the 55-document limit** and has an effectively unrestricted capacity.

Its best use is narrow but valuable: **directing the analyst to specific sections within a document** — the exact page or clause where a quantitative target appears, or where a confidentiality clause is documented. Everything material must be in the uploaded documents; the comment gives context to what is already there, never new standalone claims. Keep comments as brief as possible: a precise reference beats a lengthy explanation.""",
  "fr": """Les analystes EcoVadis lisent les champs de commentaire, mais **aucun point n'est jamais attribué sur la seule base d'un commentaire** — le champ complète la documentation, il ne la remplace pas. Un commentaire bien écrit à côté d'un document faible ou manquant n'améliorera pas le score de la question. Le champ est **hors limite des 55 documents** et sa capacité est pratiquement illimitée.

Son meilleur usage est étroit mais précieux : **diriger l'analyste vers les sections précises d'un document** — la page ou la clause exacte où figure un objectif chiffré, ou l'endroit où une clause de confidentialité est documentée. Tout élément matériel doit être dans les documents chargés ; le commentaire contextualise ce qui s'y trouve, sans jamais introduire d'affirmation autonome. Restez aussi bref que possible : une référence précise vaut mieux qu'une longue explication.""",
  "nl": """De EcoVadis-analisten lezen de commentaarvelden, maar **punten worden nooit op basis van commentaar alleen toegekend** — het veld vult de documentatie aan, het vervangt ze niet. Een goed geschreven commentaar naast een zwak of ontbrekend document verbetert de score voor die vraag niet. Het veld valt **buiten de limiet van 55 documenten** en heeft een praktisch onbeperkte capaciteit.

Het beste gebruik is smal maar waardevol: **de analist naar de precieze secties van een document leiden** — de exacte pagina of clausule met het becijferde doel, of de plaats waar een vertrouwelijkheidsclausule is gedocumenteerd. Al het materiële moet in de opgeladen documenten staan; het commentaar geeft context bij wat er al is, nooit nieuwe op zichzelf staande beweringen. Houd commentaren zo kort mogelijk: een precieze verwijzing verslaat een lange uitleg."""},
 "topics": ["questionnaire", "preuves"],
 "keywords": {"en": ["comment field", "free text", "55-document limit", "analyst guidance"],
              "fr": ["champ commentaire", "texte libre", "limite 55 documents", "orientation analyste"],
              "nl": ["commentaarveld", "vrije tekst", "limiet 55 documenten", "analist wijzen"]},
 "source_note": SRC1 + " + " + SRC2,
 "related": ["build-strong-ecovadis-submissions-consistently"],
},
{
 "id": "kb-0129",
 "slug": {"en": "have-documentation-expectations-tightened",
          "fr": "les-exigences-documentaires-se-sont-elles-durcies",
          "nl": "zijn-de-documentatie-eisen-strenger-geworden"},
 "title": {"en": "Have documentation quality expectations become more stringent compared to previous cycles?",
           "fr": "Les exigences de qualité documentaire se sont-elles durcies par rapport aux cycles précédents ?",
           "nl": "Zijn de kwaliteitseisen voor documentatie strenger geworden dan in vorige cycli?"},
 "summary": {"en": "Yes: review standards keep moving toward genuine implementation evidence and framework-aligned data (GRI indicators, ESRS data points); the shift from 'with reference to' to 'in accordance with' reporting standards is the clearest recent signal.",
             "fr": "Oui : les standards de revue évoluent vers des preuves de mise en œuvre réelle et des données alignées sur les référentiels (GRI, ESRS) ; le passage du « with reference to » au « in accordance with » est le signal le plus net.",
             "nl": "Ja: de reviewnormen evolueren naar echt uitvoeringsbewijs en kadergebonden data (GRI-indicatoren, ESRS-datapunten); de verschuiving van 'with reference to' naar 'in accordance with' is het duidelijkste signaal."},
 "body": {
  "en": """Yes. EcoVadis's review standards have consistently moved toward **more rigorous evidence requirements**. Analysts increasingly look for documents that demonstrate genuine implementation rather than intent alone, and for data that meets recognised framework criteria such as **GRI indicators or ESRS data points**. The shift toward requiring **"in accordance with"** rather than **"with reference to"** reporting standards is the clearest recent signal of this direction — see the Rising Bar and 2026-changes articles for the full picture.""",
  "fr": """Oui. Les standards de revue d'EcoVadis évoluent constamment vers **des exigences de preuve plus rigoureuses**. Les analystes cherchent de plus en plus des documents démontrant une mise en œuvre réelle plutôt qu'une intention, et des données conformes aux critères des référentiels reconnus — **indicateurs GRI, points de données ESRS**. Le passage d'un alignement **« with reference to »** à **« in accordance with »** est le signal récent le plus net de cette direction — voir les fiches Rising Bar et « ce qui change en 2026 » pour le tableau complet.""",
  "nl": """Ja. De reviewnormen van EcoVadis evolueren voortdurend naar **strengere bewijseisen**. Analisten zoeken steeds meer documenten die echte uitvoering aantonen in plaats van louter intentie, en data die voldoet aan de criteria van erkende kaders — **GRI-indicatoren, ESRS-datapunten**. De verschuiving van **"with reference to"** naar **"in accordance with"** rapporteringsstandaarden is het duidelijkste recente signaal van die richting — zie de fiches Rising Bar en "wat verandert in 2026" voor het volledige beeld."""},
 "topics": ["rising-bar", "preuves", "methodologie"],
 "keywords": {"en": ["stricter requirements", "in accordance with", "GRI", "ESRS data points"],
              "fr": ["exigences durcies", "in accordance with", "GRI", "points de données ESRS"],
              "nl": ["strengere eisen", "in accordance with", "GRI", "ESRS-datapunten"]},
 "source_note": SRC1,
 "related": ["ecovadis-rising-standards-2026", "whats-changing-in-2026"],
},
]
